/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Comment {
  id: string;
  incident_id: string;
  author: string;
  body: string;
  mentions: string[];
  created_at: number;
}

export interface CommentRecord {
  incident_id: string;
  author: string;
  body: string;
  mentions: string[];
  created_at: number;
}

export interface Event_CommentAdded {
  id: string;
  incident_id: string;
  author: string;
}

export interface Event_IncidentAssigned {
  id: string;
  assignee: string;
}

export interface Event_IncidentCreated {
  id: string;
  created_by: string;
}

export interface Event_IncidentStatusUpdated {
  id: string;
  status: string;
}

export interface Event_PostmortemCreated {
  id: string;
  incident_id: string;
}

export interface Event_PostmortemPublished {
  id: string;
}

export interface Incident {
  id: string;
  title: string;
  description: string;
  severity: string;
  affected_area: string;
  status: string;
  assigned_to: string | null;
  created_by: string;
  created_at: number;
  updated_at: number;
}

export interface IncidentRecord {
  title: string;
  description: string;
  severity: string;
  affected_area: string;
  status: string;
  assigned_to: string;
  created_by: string;
  created_at: number;
  updated_at: number;
}

export interface IncidentTracker {
  incidents: Record<string, IncidentRecord>;
  comments: Record<string, CommentRecord>;
  postmortems: Record<string, PostmortemRecord>;
  postmortem_authors: Record<string, number>;
}

export interface Postmortem {
  id: string;
  incident_id: string;
  author: string;
  summary: string;
  root_cause: string;
  resolution_steps: string;
  lessons_learned: string;
  status: string;
  created_at: number;
}

export interface PostmortemRecord {
  incident_id: string;
  author: string;
  summary: string;
  root_cause: string;
  resolution_steps: string;
  lessons_learned: string;
  status: string;
  created_at: number;
}







export type AbiEvent =
  | { name: "IncidentCreated"; payload: Event_IncidentCreated }
  | { name: "IncidentStatusUpdated"; payload: Event_IncidentStatusUpdated }
  | { name: "IncidentAssigned"; payload: Event_IncidentAssigned }
  | { name: "CommentAdded"; payload: Event_CommentAdded }
  | { name: "PostmortemCreated"; payload: Event_PostmortemCreated }
  | { name: "PostmortemPublished"; payload: Event_PostmortemPublished }
;


export class IncidentTrackerClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * create_incident
   */
  public async createIncident(params: { title: string; description: string; severity: string; affected_area: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_incident', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * update_status
   */
  public async updateStatus(params: { incident_id: string; status: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'update_status', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * assign_incident
   */
  public async assignIncident(params: { incident_id: string; assignee: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'assign_incident', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_incidents
   */
  public async listIncidents(): Promise<Incident[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_incidents', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Incident[];
  }

  /**
   * add_comment
   */
  public async addComment(params: { incident_id: string; body: string; mentions: string[] }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'add_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * list_comments
   */
  public async listComments(params: { incident_id: string }): Promise<Comment[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_comments', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as Comment[];
  }

  /**
   * create_postmortem
   */
  public async createPostmortem(params: { incident_id: string; summary: string; root_cause: string; resolution_steps: string; lessons_learned: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_postmortem', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * publish_postmortem
   */
  public async publishPostmortem(params: { postmortem_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'publish_postmortem', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_postmortems
   */
  public async listPostmortems(): Promise<Postmortem[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_postmortems', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Postmortem[];
  }

}