// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect, type Page } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

async function ensureWorkspace(page: Page): Promise<void> {
  const noWs = await page.getByText('No workspaces yet').isVisible({ timeout: 4_000 }).catch(() => false);
  if (noWs) {
    await page.getByRole('button', { name: 'Create workspace' }).first().click();
    await page.getByRole('dialog').getByRole('button', { name: 'Create workspace' }).click();
    await expect(page.getByText('Incident Dashboard')).toBeVisible({ timeout: 15_000 });
  }
}

async function reportIncident(page: Page, title: string, severity = 'P1'): Promise<void> {
  await page.getByRole('button', { name: '\u26a1 Report Incident' }).click();
  await page.getByRole('button', { name: severity }).click();
  await page.getByPlaceholder('Brief incident title\u2026').fill(title);
  await page.getByPlaceholder('What is happening? Impact? Timeline?').fill('Automated e2e test incident');
  await page.getByRole('button', { name: 'Report Incident' }).click();
  await expect(page.getByText(title)).toBeVisible({ timeout: 10_000 });
}

test.describe(`team member: acknowledge an open incident`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await ensureWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a team member acknowledges an incident, its status changes to 'acknowledged' and the acknowledger becomes the incident commander, visible to everyone within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();

    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Ensure workspace on node 0
      await ensureWorkspace(pageA);

      // Invite node 1 if it has no workspace yet
      const noWsB = await pageB.getByText('No workspaces yet').isVisible({ timeout: 4_000 }).catch(() => false);
      if (noWsB) {
        await pageA.getByRole('button', { name: '+ Invite' }).click();
        await pageA.getByRole('button', { name: 'Generate invite code' }).click();
        await expect(pageA.locator('label', { hasText: 'Invite code' })).toBeVisible({ timeout: 10_000 });
        const code = await pageA.locator('textarea').last().inputValue();
        await pageA.keyboard.press('Escape');
        await pageB.getByRole('button', { name: 'Join with invitation' }).click();
        await pageB.getByPlaceholder('Paste your invite code\u2026').fill(code);
        await pageB.getByRole('button', { name: 'Join workspace' }).click();
        await expect(pageB.getByText('Incident Dashboard')).toBeVisible({ timeout: 15_000 });
      }

      const title = 'E2E-Ack-StatusAndCommander';

      // Node 0 reports incident
      await reportIncident(pageA, title);

      // Node 0 opens detail and acknowledges
      await pageA.getByText(title).first().click();
      await pageA.getByRole('button', { name: 'Acknowledge' }).click();

      // Node 1 sees status = 'acknowledged' on the dashboard card within 5 s
      await expect(pageB.getByText('acknowledged')).toBeVisible({ timeout: 5_000 });

      // Node 1 opens detail — commander line is present
      await pageB.getByText(title).first().click();
      await expect(pageB.getByText(/commander/i)).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });

  test(`an already-acknowledged or resolved incident cannot be acknowledged again`, async ({ page }) => {
    const title = 'E2E-Ack-NoDoubleAck';

    // Report and open the incident
    await reportIncident(page, title);
    await page.getByText(title).first().click();

    // First acknowledgement succeeds
    await page.getByRole('button', { name: 'Acknowledge' }).click();

    // Status changes to 'acknowledged'
    await expect(page.getByText('acknowledged')).toBeVisible({ timeout: 5_000 });

    // Acknowledge button is no longer rendered (canAck = false when status != 'open')
    await expect(page.getByRole('button', { name: 'Acknowledge' })).toBeHidden({ timeout: 5_000 });
  });
});
