// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team member: add a new task to the list`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a team member adds a task, every other team member sees it in their list within 5s`, async ({ browser }) => {
    // Two-actor test: node 0 creates, node 1 observes cross-node replication.
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();

    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Node 0 fills the "Add a new task…" input and submits.
      await pageA.getByPlaceholder('Add a new task…').fill('Fix login bug');
      await pageA.getByRole('button', { name: '+ Add' }).click();

      // Confirm the task appeared for node 0 before asserting replication.
      await expect(pageA.getByText('Fix login bug')).toBeVisible({ timeout: 5_000 });

      // Node 1 must see the same task within 5 s.
      await expect(pageB.getByText('Fix login bug')).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
