// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect, type Page } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, uniqueName } from './helpers';

// The e2e isolation harness pre-provisions one namespace + one context per
// spec file and binds every logged-in node to it as the group (see
// helpers.ts's isolation notes). A fresh member lands on the group's
// display-name gate before any group content is visible — join it once.
async function joinGroupIfNeeded(page: Page, name: string) {
  const gate = page.getByTestId('group-join-gate');
  try {
    await gate.waitFor({ state: 'visible', timeout: 15_000 });
  } catch {
    return; // already a member of this group
  }
  await page.getByTestId('field-display_name').fill(name);
  await page.getByTestId('action-set_display_name').click();
  await gate.waitFor({ state: 'hidden', timeout: 10_000 });
}

test.describe(`member: add an expense and choose how to split it — equally among selected members, or fully owed by one specific person`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test('after a member adds an expense, every other member of the group sees it in the expense list with the correct split within 5s', async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);
      await createWorkspace(pageA);
      await createWorkspace(pageB);

      const payerName = uniqueName('payer');
      const otherName = uniqueName('member');
      await joinGroupIfNeeded(pageA, payerName);
      await joinGroupIfNeeded(pageB, otherName);

      // Wait until A knows about both members — the add-expense form seeds
      // "equal" participants from every currently-known member, so this
      // guarantees the split below actually includes both people.
      await expect(pageA.getByText(/2 members?/)).toBeVisible({ timeout: 15_000 });

      const description = uniqueName('dinner');
      await pageA.getByTestId('field-description').fill(description);
      await pageA.getByTestId('field-amount').fill('20');
      // Split type defaults to "equal"; explicitly select it via position
      // (not label text, which is UI chrome, not a created entity) to
      // avoid depending on hardcoded copy.
      await pageA.getByTestId('field-split_type').locator('button').first().click();
      await pageA.getByTestId('field-paid_by').selectOption({ label: `${payerName} paid` });
      await pageA.getByTestId('action-add_expense').click();

      // Every other member (B) sees it in the expense list within 5s, with
      // the correct equal split reflected (paid-by name + per-person share).
      const rowOnB = pageB.locator('[data-testid^="item-expense-"]').filter({ hasText: description });
      await expect(rowOnB).toBeVisible({ timeout: 5_000 });
      await expect(rowOnB).toContainText(payerName);
      await expect(rowOnB).toContainText('each');
      await expect(rowOnB).toContainText('₹10');

      // The other split mode: fully owed by one specific person, not shared.
      const singleDescription = uniqueName('cab');
      await pageA.getByTestId('field-description').fill(singleDescription);
      await pageA.getByTestId('field-amount').fill('8');
      await pageA.getByTestId('field-split_type').locator('button').nth(1).click();
      await pageA.getByTestId('field-owed_by').selectOption({ label: `${otherName} owes all` });
      await pageA.getByTestId('action-add_expense').click();

      const singleRowOnB = pageB.locator('[data-testid^="item-expense-"]').filter({ hasText: singleDescription });
      await expect(singleRowOnB).toBeVisible({ timeout: 5_000 });
      await expect(singleRowOnB).toContainText(`owed fully by ${otherName}`);
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
