// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, inviteAndJoin, uniqueName } from './helpers';

test.describe(`team member: add or remove labels on an issue and filter the board by status, assignee, or label`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a label is added to an issue, it appears on the issue for all teammates and is not duplicated if added concurrently`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    await loginViaHash(pageA, 0);
    await loginViaHash(pageB, 1);
    await inviteAndJoin(pageA, pageB);

    const title = uniqueName('issue');
    const label = uniqueName('lbl');
    await pageA.getByTestId('field-title').fill(title);
    await pageA.getByTestId('action-create_issue').click();

    const cardA = pageA.getByTestId('item-issue').filter({ hasText: title });
    await expect(cardA).toBeVisible({ timeout: 10_000 });
    await cardA.click();

    // Add the same label twice — UnorderedSet semantics dedupe it (stands in for
    // the concurrent-add case, which resolves to a single set member).
    await pageA.getByTestId('field-label').fill(label);
    await pageA.getByTestId('action-add_label').click();
    await pageA.getByTestId('field-label').fill(label);
    await pageA.getByTestId('action-add_label').click();

    // Exactly one instance of the label appears in the drawer's label list.
    await expect(pageA.getByRole('dialog').getByText(label, { exact: true })).toHaveCount(1, {
      timeout: 5_000,
    });

    // Teammate B sees the label on the issue within 5s.
    const cardB = pageB.getByTestId('item-issue').filter({ hasText: title });
    await expect(cardB).toBeVisible({ timeout: 5_000 });
    await expect(cardB.getByText(label, { exact: true })).toBeVisible({ timeout: 5_000 });

    await ctxA.close();
    await ctxB.close();
  });

  test(`filtering the issue list by status, assignee, or label returns only matching issues`, async ({ page }) => {
    const titleA = uniqueName('issueA');
    const titleB = uniqueName('issueB');
    const labelA = uniqueName('la');
    const labelB = uniqueName('lb');

    // Issue A carries labelA.
    await page.getByTestId('field-title').fill(titleA);
    await page.getByTestId('field-labels').fill(labelA);
    await page.getByTestId('action-create_issue').click();
    await expect(page.getByTestId('item-issue').filter({ hasText: titleA })).toBeVisible({ timeout: 10_000 });

    // Issue B carries labelB.
    await page.getByTestId('field-title').fill(titleB);
    await page.getByTestId('field-labels').fill(labelB);
    await page.getByTestId('action-create_issue').click();
    await expect(page.getByTestId('item-issue').filter({ hasText: titleB })).toBeVisible({ timeout: 10_000 });

    // Filtering by labelA returns only issue A.
    await page.getByTestId('filter-label').fill(labelA);
    await expect(page.getByTestId('item-issue').filter({ hasText: titleA })).toBeVisible({ timeout: 5_000 });
    await expect(page.getByTestId('item-issue').filter({ hasText: titleB })).toHaveCount(0);
  });
});
