// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team lead: assign a task to a specific teammate`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a lead assigns a task to a teammate, the assignee sees the task marked as theirs, and all other members see the assignment within 5s`, async ({ browser }) => {
    // Two-actor test: node 0 creates + assigns a task to itself ("You (you)" option
    // representing the lead's own identity); node 1 observes the "→ …" assignment chip.
    // [Verifier] NOTE: The assign dropdown's "You (you)" option maps to node-0's own
    // identity — this exercises the cross-node assignment visibility requirement.
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();

    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Node 0 creates a task.
      await pageA.getByPlaceholder('Add a new task…').fill('Implement feature X');
      await pageA.getByRole('button', { name: '+ Add' }).click();
      await expect(pageA.getByText('Implement feature X')).toBeVisible({ timeout: 5_000 });

      // Node 1 confirms the task synced before the assign action.
      await expect(pageB.getByText('Implement feature X')).toBeVisible({ timeout: 5_000 });

      // Node 0 opens the assign panel (👤 button, title="Assign task").
      await pageA.getByTitle('Assign task').first().click();

      // Select the first non-empty assignee option ("You (you)" = selfIdentity of node 0).
      await pageA.locator('select').selectOption({ index: 1 });

      // Confirm the assignment.
      await pageA.getByRole('button', { name: 'Assign' }).click();

      // The assignee chip "→ …" must appear for node 0 (the assignee sees it marked as theirs).
      await expect(pageA.getByText(/→/)).toBeVisible({ timeout: 5_000 });

      // All other members (node 1) must see the assignment chip within 5 s.
      await expect(pageB.getByText(/→/)).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
