// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, inviteAndJoin, uniqueName } from './helpers';

test.describe(`team member: change an issue's status among Open, In progress, Blocked, and Done`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`when anyone changes an issue's status, all teammates see the issue move columns within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    await loginViaHash(pageA, 0);
    await loginViaHash(pageB, 1);
    await inviteAndJoin(pageA, pageB);

    const title = uniqueName('issue');
    await pageA.getByTestId('field-title').fill(title);
    await pageA.getByTestId('action-create_issue').click();

    const cardA = pageA.getByTestId('item-issue').filter({ hasText: title });
    await expect(cardA).toBeVisible({ timeout: 10_000 });
    await cardA.click();
    // Move the issue from Open → In progress.
    await pageA.getByTestId('action-set_status').selectOption('In progress');

    // Teammate B sees the issue and, when opened, it now sits in In progress.
    const cardB = pageB.getByTestId('item-issue').filter({ hasText: title });
    await expect(cardB).toBeVisible({ timeout: 5_000 });
    await cardB.click();
    await expect(pageB.getByTestId('action-set_status')).toHaveValue('In progress', { timeout: 5_000 });

    await ctxA.close();
    await ctxB.close();
  });

  test(`status can only be one of Open, In progress, Blocked, Done; other values are rejected`, async ({ page }) => {
    const title = uniqueName('issue');
    await page.getByTestId('field-title').fill(title);
    await page.getByTestId('action-create_issue').click();

    const card = page.getByTestId('item-issue').filter({ hasText: title });
    await expect(card).toBeVisible({ timeout: 10_000 });
    await card.click();

    // The status control only offers the four valid values — any other value is
    // not selectable, so invalid statuses are rejected at the boundary.
    const options = await page.getByTestId('action-set_status').locator('option').allInnerTexts();
    expect(options.map((o) => o.trim())).toEqual(['Open', 'In progress', 'Blocked', 'Done']);
  });
});
