// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team lead: clear all completed tasks at once`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  // [Verifier] NOTE: "Clear completed" button is not yet present in the
  // frontend — the current UI is the chat foundation shell. Promote from
  // fixme once TaskListPage ships the clear-completed control and completed
  // section so cross-node removal can be observed.
  test.fixme(`after the team lead clears completed tasks, all tasks marked as done are removed and every member sees the updated list`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0); // team lead
      await loginViaHash(pageB, 1); // other member

      // Team lead adds two tasks and completes them
      await pageA.getByPlaceholder('Add a task').fill('Task One');
      await pageA.getByRole('button', { name: 'Add' }).click();
      await pageA.getByRole('checkbox', { name: 'Task One' }).click();

      await pageA.getByPlaceholder('Add a task').fill('Task Two');
      await pageA.getByRole('button', { name: 'Add' }).click();
      await pageA.getByRole('checkbox', { name: 'Task Two' }).click();

      // Team lead clears all completed
      await pageA.getByRole('button', { name: /clear completed/i }).click();

      // Both tasks should be gone from both nodes
      await expect(pageB.getByText('Task One')).toBeHidden({ timeout: 5_000 });
      await expect(pageB.getByText('Task Two')).toBeHidden({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
