// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`teammate: comment on someone's blocker`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a teammate posts a comment on a standup, every member sees the comment attached to that standup within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const ctxC = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    const pageC = await ctxC.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);
      await loginViaHash(pageC, 2);

      // Node A: post a standup with a blocker
      await pageA.getByTestId('field-done_items').fill('Finished API integration');
      await pageA.getByTestId('field-blockers').fill('Need DB credentials from ops');
      await pageA.getByTestId('field-planned_items').fill('Write integration tests');
      await pageA.getByTestId('field-date').fill('2025-01-15');
      await pageA.getByTestId('action-post_standup').click();

      // Node B: wait for the standup to appear, then post a comment on it
      const standupOnB = pageB.getByTestId('item-StandupEntry').filter({ hasText: 'Need DB credentials from ops' });
      await expect(standupOnB).toBeVisible({ timeout: 5_000 });

      // Fill in the comment body and submit
      await standupOnB.getByTestId('field-body').fill('I can help with the API keys — ping me');
      await standupOnB.getByTestId('action-add_comment').click();

      // Node C: the comment should be visible on that standup within 5s
      const standupOnC = pageC.getByTestId('item-StandupEntry').filter({ hasText: 'Need DB credentials from ops' });
      await expect(standupOnC).toBeVisible({ timeout: 5_000 });
      await expect(
        pageC.getByTestId('item-Comment').filter({ hasText: 'I can help with the API keys — ping me' })
      ).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
      await ctxC.close();
    }
  });
});
