// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team lead: create a new list and invite my teammates`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after the team lead creates the list and invites a teammate, the teammate sees the shared list appear within 5s`, async ({ browser }) => {
    // Multi-actor: team lead (node 0) creates a workspace and invites a teammate;
    // teammate (node 1) joins and must see "Team Tasks" within 5s.
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      // Team lead logs in.
      await loginViaHash(pageA, 0);

      // Create a workspace if one doesn't exist yet.
      const hasWorkspace = await pageA.getByText('Team Tasks').isVisible();
      if (!hasWorkspace) {
        await pageA.getByRole('button', { name: 'Create workspace' }).click();
        await pageA.getByRole('dialog').getByRole('button', { name: 'Create workspace' }).click();
        await expect(pageA.getByText('Team Tasks')).toBeVisible({ timeout: 15_000 });
      }

      // Open invite modal, generate an invite code, read it from the textarea.
      await pageA.getByRole('button', { name: 'Invite teammate' }).click();
      await pageA.getByRole('button', { name: 'Generate invite code' }).click();
      const inviteCode = await pageA.getByRole('dialog').locator('textarea').inputValue({ timeout: 10_000 });
      await pageA.getByLabel('Close').click();

      // Teammate (node 1) logs in and joins with the invite code.
      await loginViaHash(pageB, 1);
      await pageB.getByRole('button', { name: 'Join with invitation' }).click();
      await pageB.getByLabel('Invite code').fill(inviteCode);
      await pageB.getByRole('button', { name: 'Join workspace' }).click();

      // Criterion: teammate sees the shared list appear within 5s.
      await expect(pageB.getByText('Team Tasks')).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
