// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';
import { ensureBoard, mintInvite, openSecondMember, RETRO_NAME } from './retro-helpers';

test.describe(`facilitator: create a retro for my team and send them the link`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after the facilitator creates a retro, every invited teammate sees it appear in their list within 5s`, async ({ page, browser }) => {
    // page is already logged in as node 0 (the facilitator) by beforeEach.
    await ensureBoard(page, RETRO_NAME);
    const code = await mintInvite(page);

    // A teammate on node 1 joins via the invite link.
    const { ctx: ctxB, page: pageB } = await openSecondMember(browser, code, 1);

    // The retro appears for the teammate — its name is the board header.
    await expect(pageB.getByRole('heading', { name: RETRO_NAME })).toBeVisible({ timeout: 15_000 });

    await ctxB.close();
  });
});
