// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, inviteAndJoin } from './helpers';

test.describe(`team member: create categories and move tasks between them`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a member creates a category or moves a task into it, everyone sees the updated grouping within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    await loginViaHash(pageA, 0);
    await loginViaHash(pageB, 1);
    await inviteAndJoin(pageA, pageB);

    // A creates two categories; B must see the new grouping within 5s.
    await pageA.getByTestId('field-name').fill('Backlog');
    await pageA.getByTestId('action-create_category').click();
    await expect(pageB.locator('[data-testid^="item-category-"]').filter({ hasText: 'Backlog' })).toBeVisible({ timeout: 5_000 });

    await pageA.getByTestId('field-name').fill('In Progress');
    await pageA.getByTestId('action-create_category').click();
    await expect(pageB.locator('[data-testid^="item-category-"]').filter({ hasText: 'In Progress' })).toBeVisible({ timeout: 5_000 });

    // A files a task into Backlog, then moves it to In Progress.
    await pageA.getByTestId('field-title').fill('Write onboarding docs');
    await pageA.getByTestId('field-category_id').selectOption({ label: 'Backlog' });
    await pageA.getByTestId('field-assignee').fill('alice');
    await pageA.getByTestId('action-create_task').click();
    const taskCardA = pageA.locator('[data-testid^="item-task-"]').filter({ hasText: 'Write onboarding docs' });
    await expect(taskCardA).toBeVisible({ timeout: 10_000 });
    await taskCardA.click();

    const detailDialogA = pageA.getByRole('dialog');
    await detailDialogA.getByTestId('field-category_id').selectOption({ label: 'In Progress' });
    await detailDialogA.getByTestId('action-move_task').click();

    // B sees the task under its new category within 5s.
    const inProgressColumnB = pageB.locator('[data-testid^="item-category-"]').filter({ hasText: 'In Progress' });
    await expect(inProgressColumnB.getByText('Write onboarding docs')).toBeVisible({ timeout: 5_000 });
    const backlogColumnB = pageB.locator('[data-testid^="item-category-"]').filter({ hasText: 'Backlog' });
    await expect(backlogColumnB.getByText('Write onboarding docs')).toHaveCount(0);

    await ctxA.close();
    await ctxB.close();
  });
});
