// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, inviteAndJoin, uniqueName } from './helpers';

test.describe(`team member or script: create an issue with a title, description, priority, and optional labels and get back its id`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after an issue is created, every teammate sees it on the board within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    await loginViaHash(pageA, 0);
    await loginViaHash(pageB, 1);
    // Put both nodes in ONE shared workspace so B can observe A's writes.
    await inviteAndJoin(pageA, pageB);

    const title = uniqueName('issue');
    await pageA.getByTestId('field-title').fill(title);
    await pageA.getByTestId('action-create_issue').click();

    // Teammate B sees the new issue on the board within 5s.
    await expect(
      pageB.getByTestId('item-issue').filter({ hasText: title }),
    ).toBeVisible({ timeout: 5_000 });

    await ctxA.close();
    await ctxB.close();
  });

  test(`creating an issue returns a unique issue id that can be used in later calls`, async ({ page }) => {
    const title = uniqueName('issue');
    await page.getByTestId('field-title').fill(title);
    await page.getByTestId('action-create_issue').click();

    const card = page.getByTestId('item-issue').filter({ hasText: title });
    await expect(card).toBeVisible({ timeout: 10_000 });

    // The created issue carries a concrete id...
    const id = await card.getAttribute('data-issue-id');
    expect(id).toBeTruthy();

    // ...that is usable in later calls: opening the card reads it back (get_issue).
    await card.click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await expect(page.getByTestId('field-body')).toBeVisible();
  });

  test(`a new issue starts in status Open`, async ({ page }) => {
    const title = uniqueName('issue');
    await page.getByTestId('field-title').fill(title);
    await page.getByTestId('action-create_issue').click();

    const card = page.getByTestId('item-issue').filter({ hasText: title });
    await expect(card).toBeVisible({ timeout: 10_000 });

    // Open the detail drawer — a freshly created issue's status control reads Open.
    await card.click();
    await expect(page.getByTestId('action-set_status')).toHaveValue('Open');
  });
});
