// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`the person who posted a kudos: delete my own note if I made a mistake`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a member deletes their own kudos, it disappears from everyone's feed within 2s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // A posts kudos
      await pageA.getByPlaceholder('Who deserves kudos? (name or @handle)').fill('DeleteTarget');
      await pageA.getByPlaceholder('Why do they deserve it?').fill('This will be deleted');
      await pageA.getByRole('button', { name: '✨ Give kudos' }).click();
      await expect(pageA.getByText('🌟 DeleteTarget')).toBeVisible({ timeout: 5_000 });

      // B sees it first
      await expect(pageB.getByText('🌟 DeleteTarget')).toBeVisible({ timeout: 2_000 });

      // A deletes their own kudos (delete button only visible to the author)
      await pageA.getByLabel('Delete this kudos').first().click();

      // Disappears from B's feed within 2s
      await expect(pageB.getByText('🌟 DeleteTarget')).toBeHidden({ timeout: 2_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });

  test(`a member cannot delete another member's kudos`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // A posts kudos
      await pageA.getByPlaceholder('Who deserves kudos? (name or @handle)').fill('ProtectedKudos');
      await pageA.getByPlaceholder('Why do they deserve it?').fill('Cannot be deleted by others');
      await pageA.getByRole('button', { name: '✨ Give kudos' }).click();

      // B sees the kudos but has no delete button — author !== B's executorPublicKey
      await expect(pageB.getByText('🌟 ProtectedKudos')).toBeVisible({ timeout: 2_000 });
      await expect(pageB.getByLabel('Delete this kudos')).toBeHidden();
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
