// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, uniqueName, inviteAndJoin } from './helpers';

// Minimal 1x1 transparent PNG, used to fill the mockup upload's file input.
const PNG_1x1 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
  'base64',
);

test.describe(`teammate: drop a pin at an exact spot on the mockup and leave a comment`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a teammate adds a pin at a position, every other teammate sees it at that same position within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const teammateA = await ctxA.newPage();
    const teammateB = await ctxB.newPage();
    await loginViaHash(teammateA, 0);
    await loginViaHash(teammateB, 1);

    await inviteAndJoin(teammateA, teammateB);

    // A mockup must exist before a pin can be dropped on it.
    const title = uniqueName('mockup');
    await teammateA.getByTestId('field-title').fill(title);
    await teammateA.getByTestId('field-image').setInputFiles({
      name: 'mockup.png',
      mimeType: 'image/png',
      buffer: PNG_1x1,
    });
    await teammateA.getByTestId('action-upload_mockup').click();
    await expect(teammateA.getByTestId('item-mockup').filter({ hasText: title })).toBeVisible({ timeout: 10_000 });

    // Drop a pin at an exact spot on the mockup canvas (the image sits inside
    // the clickable frame; clicking at a fixed offset picks an exact x/y).
    const imgA = teammateA.locator('img').first();
    await imgA.waitFor({ state: 'visible', timeout: 10_000 });
    const frameA = imgA.locator('xpath=..');
    await frameA.click({ position: { x: 40, y: 60 } });

    const text = uniqueName('pin-comment');
    await teammateA.getByTestId('field-text').fill(text);
    await teammateA.getByTestId('action-add_pin').click();

    // The marker's title attribute carries the pin's own text, so it's a
    // stable, unique handle for the exact pin we just created.
    const markerA = teammateA.locator(`[title="${text}"]`);
    await expect(markerA).toBeVisible({ timeout: 10_000 });
    const styleA = await markerA.getAttribute('style');

    // Teammate B: switch to the same mockup and confirm the pin renders at
    // the identical position. The marker's left/top % are derived directly
    // from the stored x/y, so an identical style string proves the same spot.
    await teammateB.getByTestId('item-mockup').filter({ hasText: title }).click();
    const markerB = teammateB.locator(`[title="${text}"]`);
    await expect(markerB).toBeVisible({ timeout: 5_000 });
    await expect(markerB).toHaveAttribute('style', styleA ?? '');

    await ctxA.close();
    await ctxB.close();
  });
});
