// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, uniqueName, inviteAndJoin } from './helpers';

test.describe(`household member: edit or remove logins I added`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`a member can only edit or delete entries they added; attempts on other members' entries are rejected`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    await loginViaHash(pageA, 0);
    await loginViaHash(pageB, 1);

    await inviteAndJoin(pageA, pageB);

    const serviceName = uniqueName('service');
    await pageA.getByTestId('field-service_name').fill(serviceName);
    await pageA.getByTestId('field-username').fill('family@home.com');
    await pageA.getByTestId('field-secret').fill('s3cr3t!');
    await pageA.getByTestId('action-add_entry').click();

    // The owner (node A) sees edit/delete controls on their own entry.
    const rowOnA = pageA.locator('[data-testid^="item-vaultentry-"]').filter({ hasText: serviceName });
    await expect(rowOnA).toBeVisible({ timeout: 10_000 });
    await expect(rowOnA.getByTestId('action-delete_entry')).toBeVisible();
    await expect(rowOnA.getByTestId('open-edit-btn')).toBeVisible();

    // A non-owner (node B) sees the entry, but has no edit/delete affordance
    // for it — the frontend rejects the attempt by not exposing the controls.
    const rowOnB = pageB.locator('[data-testid^="item-vaultentry-"]').filter({ hasText: serviceName });
    await expect(rowOnB).toBeVisible({ timeout: 5_000 });
    await expect(rowOnB.getByTestId('action-delete_entry')).toHaveCount(0);
    await expect(rowOnB.getByTestId('open-edit-btn')).toHaveCount(0);

    await clearAuth(pageA);
    await clearAuth(pageB);
    await ctxA.close();
    await ctxB.close();
  });
});
