// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team member: edit or add tags to my own documents`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a member edits tags on a document they created, every other team member sees the updated tags within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();

    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // A creates a document
      await pageA.getByRole('button', { name: '+ New' }).click();
      await pageA.getByPlaceholder('Document title…').fill('Tag Edit Doc');
      await pageA.getByRole('button', { name: 'Create' }).click();
      await expect(pageA.getByPlaceholder('add tag…')).toBeVisible({ timeout: 10_000 });

      // A adds an initial tag
      await pageA.getByPlaceholder('add tag…').fill('initial-tag');
      await pageA.getByRole('button', { name: '+' }).click();
      await expect(pageA.getByText('#initial-tag')).toBeVisible({ timeout: 10_000 });

      // B sees the initial tag on the document within 5 s
      await expect(pageB.getByText('#initial-tag')).toBeVisible({ timeout: 5_000 });

      // A adds a new tag (editing the document's tags)
      await pageA.getByPlaceholder('add tag…').fill('updated-tag');
      await pageA.getByRole('button', { name: '+' }).click();
      await expect(pageA.getByText('#updated-tag')).toBeVisible({ timeout: 10_000 });

      // B sees the newly added tag within 5 s
      await expect(pageB.getByText('#updated-tag')).toBeVisible({ timeout: 5_000 });
    } finally {
      await clearAuth(pageA);
      await clearAuth(pageB);
      await ctxA.close();
      await ctxB.close();
    }
  });
});
