// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect, Page } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

// This app gates all standup/dashboard UI behind a per-namespace workspace:
// a fresh node has no context yet, so it lands on a "Welcome" screen with
// "Create workspace" / "Join with invitation" buttons. Peers join the same
// workspace via an invite code minted from the TopBar "Invite" button.
// Clicking "Create workspace" flips `ws.loading` synchronously (bootstrap()
// calls setBootstrapping(true) before any await), and the Welcome screen only
// renders while `!ws.ready && !ws.loading`. Combined with the namespace/
// context discovery polling still settling right after login, the button can
// mount/unmount a few times in the first couple of seconds — Playwright
// reports this as "element was detached from the DOM, retrying" and gives up
// after the 15s action timeout. Poll-click across a longer window instead of
// a single click, bailing out as soon as the resulting Dashboard tab appears
// (bootstrap() is idempotent via an internal ref guard, so re-clicking is safe).
async function createWorkspace(page: Page) {
  const dashboardBtn = page.getByRole('button', { name: 'Dashboard' });
  const deadline = Date.now() + 45_000;
  while (Date.now() < deadline) {
    if (await dashboardBtn.isVisible().catch(() => false)) return;
    await page
      .getByRole('button', { name: 'Create workspace' })
      .click({ timeout: 3_000 })
      .catch(() => { /* button mid-remount from a settling poll — retry */ });
    if (await dashboardBtn.isVisible({ timeout: 2_000 }).catch(() => false)) return;
  }
  await expect(dashboardBtn).toBeVisible({ timeout: 15_000 });
}

async function inviteAndJoin(hostPage: Page, joinerPage: Page) {
  // Host mints a shareable invite code for its workspace namespace.
  await hostPage.getByRole('button', { name: 'Invite' }).click();
  await hostPage.getByRole('button', { name: 'Generate invite code' }).click();
  const codeBox = hostPage.locator('textarea[readonly]');
  await expect(codeBox).not.toHaveValue('', { timeout: 10_000 });
  const code = await codeBox.inputValue();
  await hostPage.getByRole('button', { name: 'Close' }).click().catch(() => {});

  // Merod persists joined namespaces across this serial run, so on a later
  // test the joiner may already have resolved into the shared workspace
  // (everyone converges on the host's single namespace) and land straight on
  // the Dashboard — nothing to re-join. Otherwise it sits on the "Welcome"
  // gate whose "Join with invitation" button mounts/unmounts while namespace/
  // context discovery settles (the same remount race createWorkspace poll-
  // clicks around). A single click hits a detached element and times out, so
  // poll-click across a longer window and bail out as soon as the Dashboard
  // tab appears.
  const dashboard = joinerPage.getByRole('button', { name: 'Dashboard' });
  const codeInput = joinerPage.getByPlaceholder('Paste your invite code…');
  const welcomeJoin = joinerPage.getByRole('button', { name: 'Join with invitation' });
  const deadline = Date.now() + 45_000;
  while (Date.now() < deadline) {
    if (await dashboard.isVisible().catch(() => false)) return;
    if (!(await codeInput.isVisible().catch(() => false))) {
      await welcomeJoin.click({ timeout: 3_000 }).catch(() => { /* mid-remount — retry */ });
    }
    if (await codeInput.isVisible({ timeout: 1_000 }).catch(() => false)) {
      await codeInput.fill(code);
      await joinerPage.getByRole('button', { name: 'Join workspace' }).click().catch(() => {});
      if (await dashboard.isVisible({ timeout: 20_000 }).catch(() => false)) return;
    }
  }
  await expect(dashboard).toBeVisible({ timeout: 15_000 });
}

test.describe(`team member: edit or delete my own standup entries`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`a member can only edit or delete standups they authored; attempts on other members' standups are rejected`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      await createWorkspace(pageA);
      await inviteAndJoin(pageA, pageB);

      // Node A: post a standup
      await pageA.getByRole('button', { name: 'Post Standup' }).click();
      await pageA.getByTestId('field-done_items').fill('Node A done items');
      await pageA.getByTestId('field-blockers').fill('Node A blocker');
      await pageA.getByTestId('field-planned_items').fill('Node A plans');
      await pageA.getByTestId('field-date').fill('2025-01-15');
      await pageA.getByTestId('action-post_standup').click();

      // Node B: wait for the standup to appear on the dashboard
      const standupOnB = pageB.getByTestId(/^item-StandupEntry-/).filter({ hasText: 'Node A done items' });
      await expect(standupOnB).toBeVisible({ timeout: 5_000 });

      // Node B: edit/delete controls for another author's standup should not
      // be accessible — the authored ownership model only renders the
      // ".actions" (Edit/Delete) block when `isOwn` is true.
      const editVisible = await standupOnB.getByRole('button', { name: 'Edit standup' }).isVisible().catch(() => false);
      const deleteVisible = await standupOnB.getByTestId('action-delete_standup').isVisible().catch(() => false);
      expect(editVisible).toBe(false);
      expect(deleteVisible).toBe(false);

      // Node A: its own standup should have accessible edit/delete controls
      const ownItem = pageA.getByTestId(/^item-StandupEntry-/).filter({ hasText: 'Node A done items' });
      await expect(ownItem).toBeVisible({ timeout: 5_000 });
      await expect(ownItem.getByRole('button', { name: 'Edit standup' })).toBeVisible();
      await expect(ownItem.getByTestId('action-delete_standup')).toBeVisible();
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });

  test(`after editing a standup, the updated content is visible to everyone within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      await createWorkspace(pageA);
      await inviteAndJoin(pageA, pageB);

      // Node A: post a standup
      await pageA.getByRole('button', { name: 'Post Standup' }).click();
      await pageA.getByTestId('field-done_items').fill('Original done items');
      await pageA.getByTestId('field-blockers').fill('Original blocker');
      await pageA.getByTestId('field-planned_items').fill('Original plans');
      await pageA.getByTestId('field-date').fill('2025-01-15');
      await pageA.getByTestId('action-post_standup').click();

      // Wait for the standup to appear on node A's own dashboard view
      const ownItem = pageA.getByTestId(/^item-StandupEntry-/).filter({ hasText: 'Original done items' });
      await expect(ownItem).toBeVisible({ timeout: 5_000 });

      // Node A: open the edit form for its own standup (card header "Edit standup" button)
      await ownItem.getByRole('button', { name: 'Edit standup' }).click();

      // Fill in updated values and save (edit mode has no date field)
      await pageA.getByTestId('field-done_items').fill('Shipped login flow + tests');
      await pageA.getByTestId('field-blockers').fill('Waiting on API keys from infra');
      await pageA.getByTestId('field-planned_items').fill('Start dashboard layout');
      await pageA.getByTestId('action-edit_standup').click();

      // Node B: updated content should be visible within 5s
      await expect(
        pageB.getByTestId(/^item-StandupEntry-/).filter({ hasText: 'Shipped login flow + tests' })
      ).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
