// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, uniqueName, inviteAndJoin } from './helpers';

// Minimal 1x1 transparent PNG, used to fill the mockup upload's file input.
const PNG_1x1 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
  'base64',
);

test.describe(`teammate: edit or remove a comment I left`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`a teammate can only edit or delete pins they authored; attempts on other teammates' pins are rejected`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const teammateA = await ctxA.newPage();
    const teammateB = await ctxB.newPage();
    await loginViaHash(teammateA, 0);
    await loginViaHash(teammateB, 1);

    await inviteAndJoin(teammateA, teammateB);

    const title = uniqueName('mockup');
    await teammateA.getByTestId('field-title').fill(title);
    await teammateA.getByTestId('field-image').setInputFiles({
      name: 'mockup.png',
      mimeType: 'image/png',
      buffer: PNG_1x1,
    });
    await teammateA.getByTestId('action-upload_mockup').click();
    await expect(teammateA.getByTestId('item-mockup').filter({ hasText: title })).toBeVisible({ timeout: 10_000 });

    const text = uniqueName('pin-comment');
    const imgA = teammateA.locator('img').first();
    await imgA.waitFor({ state: 'visible', timeout: 10_000 });
    await imgA.locator('xpath=..').click({ position: { x: 40, y: 60 } });
    await teammateA.getByTestId('field-text').fill(text);
    await teammateA.getByTestId('action-add_pin').click();
    await expect(teammateA.getByTestId('item-pin').filter({ hasText: text })).toBeVisible({ timeout: 10_000 });

    // B, who did not author this pin, sees it but has no edit/delete controls.
    await teammateB.getByTestId('item-mockup').filter({ hasText: title }).click();
    const rowB = teammateB.getByTestId('item-pin').filter({ hasText: text });
    await expect(rowB).toBeVisible({ timeout: 5_000 });
    await expect(rowB.getByTestId('action-remove_pin')).toHaveCount(0);
    await expect(rowB.getByRole('button', { name: 'Edit' })).toHaveCount(0);

    // A, the author, can edit the pin they created.
    const rowA = teammateA.getByTestId('item-pin').filter({ hasText: text });
    await rowA.getByRole('button', { name: 'Edit' }).click();
    const editedText = uniqueName('pin-comment-edited');
    await rowA.getByTestId('field-text').fill(editedText);
    await rowA.getByTestId('action-edit_pin').click();
    await expect(teammateA.getByTestId('item-pin').filter({ hasText: editedText })).toBeVisible({ timeout: 5_000 });

    // A, the author, can delete the pin they created.
    await teammateA
      .getByTestId('item-pin')
      .filter({ hasText: editedText })
      .getByTestId('action-remove_pin')
      .click();
    await expect(teammateA.getByTestId('item-pin').filter({ hasText: editedText })).toHaveCount(0, { timeout: 5_000 });

    await ctxA.close();
    await ctxB.close();
  });
});
