// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect, type Page } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

async function ensureWorkspace(page: Page): Promise<void> {
  const noWs = await page.getByText('No workspaces yet').isVisible({ timeout: 4_000 }).catch(() => false);
  if (noWs) {
    await page.getByRole('button', { name: 'Create workspace' }).first().click();
    await page.getByRole('dialog').getByRole('button', { name: 'Create workspace' }).click();
    await expect(page.getByText('Incident Dashboard')).toBeVisible({ timeout: 15_000 });
  }
}

async function reportAndOpenIncident(page: Page, title: string): Promise<void> {
  await page.getByRole('button', { name: '\u26a1 Report Incident' }).click();
  await page.getByRole('button', { name: 'P1' }).click();
  await page.getByPlaceholder('Brief incident title\u2026').fill(title);
  await page.getByPlaceholder('What is happening? Impact? Timeline?').fill('Escalate test incident');
  await page.getByRole('button', { name: 'Report Incident' }).click();
  await expect(page.getByText(title)).toBeVisible({ timeout: 10_000 });
  await page.getByText(title).first().click();
}

test.describe(`team member: escalate an unacknowledged incident to the next on-call responder`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await ensureWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a team member escalates an incident, a timeline entry is logged noting the escalation and the next on-call responder is recorded on the incident`, async ({ page }) => {
    const title = 'E2E-Escalate-Timeline';

    await reportAndOpenIncident(page, title);

    // Click the "Escalate" action button in the incident detail
    await page.getByRole('button', { name: 'Escalate' }).click();

    // Escalate Incident modal appears
    await expect(page.getByText('Escalate Incident')).toBeVisible({ timeout: 5_000 });

    // Fill in the next responder ID
    await page.getByPlaceholder('member-xxxx').fill('member-b2c1');

    // Submit escalation (the WarnBtn inside the modal, last 'Escalate' button)
    await page.getByRole('button', { name: 'Escalate' }).last().click();

    // Modal closes; a timeline entry noting the escalation is logged
    await expect(page.getByText('escalation')).toBeVisible({ timeout: 10_000 });
  });

  test(`only incidents in 'open' status can be escalated`, async ({ page }) => {
    const title = 'E2E-Escalate-AckNoEscalate';

    await reportAndOpenIncident(page, title);

    // Acknowledge the incident (moves status from 'open' to 'acknowledged')
    await page.getByRole('button', { name: 'Acknowledge' }).click();
    await expect(page.getByText('acknowledged')).toBeVisible({ timeout: 5_000 });

    // Escalate button must NOT be rendered for acknowledged incidents
    // (canEscalate = inc.status === 'open' → false when acknowledged)
    await expect(page.getByRole('button', { name: 'Escalate' })).toBeHidden({ timeout: 5_000 });
  });
});
