// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team member: link a paragraph in one document to a paragraph in another`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a member selects text, creates a link, and targets text in another document, both documents show the bidirectional link and all team members see it within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();

    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // A creates two documents
      await pageA.getByRole('button', { name: '+ New' }).click();
      await pageA.getByPlaceholder('Document title…').fill('Doc Alpha');
      await pageA.getByRole('button', { name: 'Create' }).click();
      await expect(pageA.getByPlaceholder('add tag…')).toBeVisible({ timeout: 10_000 });

      await pageA.getByRole('button', { name: '+ New' }).click();
      await pageA.getByPlaceholder('Document title…').fill('Doc Beta');
      await pageA.getByRole('button', { name: 'Create' }).click();
      await expect(pageA.getByPlaceholder('add tag…')).toBeVisible({ timeout: 10_000 });

      // A navigates back to Doc Alpha (first occurrence in the sidebar doc list)
      await pageA.getByText('Doc Alpha').first().click();

      // A opens the link creation form
      await pageA.getByRole('button', { name: '🔗 Link selection' }).click();
      await expect(pageA.getByText('Create Link')).toBeVisible({ timeout: 5_000 });

      // A fills in the link form fields
      await pageA.getByLabel('Source text (from this document):').fill('alpha concept');
      await pageA.getByLabel('Target document:').selectOption({ label: 'Doc Beta' });
      await pageA.getByPlaceholder('paste or type the target passage…').fill('beta concept');
      await pageA.getByRole('button', { name: 'Create Link' }).click();

      // Doc Alpha's LINKS section is now visible (bidirectional — source side)
      await expect(pageA.getByText(/LINKS \(\d+\)/)).toBeVisible({ timeout: 10_000 });

      // Navigate to Doc Beta and verify it also shows the link (bidirectional — target side)
      await pageA.getByText('Doc Beta').first().click();
      await expect(pageA.getByText(/LINKS \(\d+\)/)).toBeVisible({ timeout: 5_000 });

      // B sees the link on Doc Alpha within 5 s
      await pageB.getByText('Doc Alpha').first().click();
      await expect(pageB.getByText(/LINKS \(\d+\)/)).toBeVisible({ timeout: 5_000 });
    } finally {
      await clearAuth(pageA);
      await clearAuth(pageB);
      await ctxA.close();
      await ctxB.close();
    }
  });
});
