// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, uniqueName } from './helpers';

test.describe(`team member or script: list issues (optionally filtered by status or assignee) and read a single issue with its comments`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`listing issues with a status or assignee filter returns only matching issues`, async ({ page }) => {
    const titleA = uniqueName('issueA');
    const titleB = uniqueName('issueB');
    const assignee = uniqueName('user');

    // Issue A — will be assigned to `assignee`.
    await page.getByTestId('field-title').fill(titleA);
    await page.getByTestId('action-create_issue').click();
    const cardA = page.getByTestId('item-issue').filter({ hasText: titleA });
    await expect(cardA).toBeVisible({ timeout: 10_000 });

    // Issue B — left unassigned.
    await page.getByTestId('field-title').fill(titleB);
    await page.getByTestId('action-create_issue').click();
    await expect(page.getByTestId('item-issue').filter({ hasText: titleB })).toBeVisible({ timeout: 10_000 });

    // Assign issue A, then close the drawer.
    await cardA.click();
    await page.getByTestId('field-assignee').fill(assignee);
    await page.getByTestId('action-set_assignee').click();
    await page.getByRole('button', { name: 'Close' }).click();

    // Filtering by assignee returns only issue A.
    await page.getByTestId('filter-assignee').fill(assignee);
    await expect(page.getByTestId('item-issue').filter({ hasText: titleA })).toBeVisible({ timeout: 5_000 });
    await expect(page.getByTestId('item-issue').filter({ hasText: titleB })).toHaveCount(0);
  });

  test(`reading a single issue returns its full details plus its comment thread ordered by created_at`, async ({ page }) => {
    const title = uniqueName('issue');
    const description = uniqueName('desc');
    const first = uniqueName('first-comment');
    const second = uniqueName('second-comment');

    await page.getByTestId('field-title').fill(title);
    await page.getByTestId('field-description').fill(description);
    await page.getByTestId('action-create_issue').click();

    const card = page.getByTestId('item-issue').filter({ hasText: title });
    await expect(card).toBeVisible({ timeout: 10_000 });
    await card.click();

    // Full details: the description is shown in the drawer.
    await expect(page.getByRole('dialog').getByText(description)).toBeVisible();

    // Post two comments in order.
    await page.getByTestId('field-body').fill(first);
    await page.getByTestId('action-add_comment').click();
    await expect(page.getByTestId('item-comment').filter({ hasText: first })).toBeVisible({ timeout: 5_000 });
    await page.getByTestId('field-body').fill(second);
    await page.getByTestId('action-add_comment').click();
    await expect(page.getByTestId('item-comment').filter({ hasText: second })).toBeVisible({ timeout: 5_000 });

    // The thread is ordered by created_at: the first comment precedes the second.
    const bodies = await page.getByTestId('item-comment').allInnerTexts();
    const i1 = bodies.findIndex((b) => b.includes(first));
    const i2 = bodies.findIndex((b) => b.includes(second));
    expect(i1).toBeGreaterThanOrEqual(0);
    expect(i2).toBeGreaterThan(i1);
  });
});
