// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, inviteAndJoin, uniqueName } from './helpers';

test.describe(`team member: log a call, email, or meeting note against a contact`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a member logs an interaction, it appears on that contact's history for all team members within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    await loginViaHash(pageA, 0);
    await loginViaHash(pageB, 1);
    await inviteAndJoin(pageA, pageB);

    const contactName = uniqueName('contact');
    await pageA.getByTestId('field-name').fill(contactName);
    await pageA.getByTestId('action-add_contact').click();
    const contactRowA = pageA.getByTestId(/^item-contact-/).filter({ hasText: contactName });
    await expect(contactRowA).toBeVisible({ timeout: 5_000 });
    await contactRowA.click();

    const note = uniqueName('note');
    await pageA.getByTestId('field-note').fill(note);
    await pageA.getByTestId('action-log_interaction').click();
    await expect(pageA.getByTestId(/^item-interaction-/).filter({ hasText: note })).toBeVisible({
      timeout: 5_000,
    });

    // B must select the same contact to view its interaction history.
    await pageB.getByTestId(/^item-contact-/).filter({ hasText: contactName }).click();
    await expect(pageB.getByTestId(/^item-interaction-/).filter({ hasText: note })).toBeVisible({
      timeout: 5_000,
    });

    await ctxA.close();
    await ctxB.close();
  });

  test(`a member can only edit or delete interactions they logged; attempts on others' entries are rejected`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    await loginViaHash(pageA, 0);
    await loginViaHash(pageB, 1);
    await inviteAndJoin(pageA, pageB);

    const contactName = uniqueName('contact');
    await pageA.getByTestId('field-name').fill(contactName);
    await pageA.getByTestId('action-add_contact').click();
    const contactRowA = pageA.getByTestId(/^item-contact-/).filter({ hasText: contactName });
    await expect(contactRowA).toBeVisible({ timeout: 5_000 });
    await contactRowA.click();

    const note = uniqueName('note');
    await pageA.getByTestId('field-note').fill(note);
    await pageA.getByTestId('action-log_interaction').click();

    const entryA = pageA.getByTestId(/^item-interaction-/).filter({ hasText: note });
    await expect(entryA).toBeVisible({ timeout: 5_000 });
    // The author can edit/delete their own entry.
    await expect(entryA.getByTestId('action-edit_interaction')).toBeVisible();
    await expect(entryA.getByTestId('action-delete_interaction')).toBeVisible();

    // B sees the same entry (once selecting the shared contact) but has no
    // edit/delete controls on an entry they did not author — the UI never
    // offers a way to attempt the mutation, so the attempt is rejected by
    // construction.
    await pageB.getByTestId(/^item-contact-/).filter({ hasText: contactName }).click();
    const entryB = pageB.getByTestId(/^item-interaction-/).filter({ hasText: note });
    await expect(entryB).toBeVisible({ timeout: 5_000 });
    await expect(entryB.getByTestId('action-edit_interaction')).toHaveCount(0);
    await expect(entryB.getByTestId('action-delete_interaction')).toHaveCount(0);

    await ctxA.close();
    await ctxB.close();
  });
});
