// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team member: mark a task as complete`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a team member checks off a task, all other members see it marked as done within 5s`, async ({ browser }) => {
    // Two-actor test: node 0 creates + completes, node 1 observes the COMPLETED section.
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();

    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Node 0 creates a task.
      await pageA.getByPlaceholder('Add a new task…').fill('Complete me');
      await pageA.getByRole('button', { name: '+ Add' }).click();
      await expect(pageA.getByText('Complete me')).toBeVisible({ timeout: 5_000 });

      // Node 1 sees the task (confirms sync before the mark-done step).
      await expect(pageB.getByText('Complete me')).toBeVisible({ timeout: 5_000 });

      // Node 0 checks the task off via the completion button (title="Mark as complete").
      await pageA.getByTitle('Mark as complete').first().click();

      // Node 0 should now show the COMPLETED section.
      await expect(pageA.getByText(/COMPLETED/)).toBeVisible({ timeout: 5_000 });

      // Node 1 must see the COMPLETED section within 5 s of node 0 checking it off.
      await expect(pageB.getByText(/COMPLETED/)).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
