// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, inviteAndJoin } from './helpers';

test.describe(`team member: mark a task complete and archive it`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a task is marked complete and archived, it moves out of the active board view for every team member`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    await loginViaHash(pageA, 0);
    await loginViaHash(pageB, 1);
    await inviteAndJoin(pageA, pageB);

    await pageA.getByTestId('field-name').fill('Ops');
    await pageA.getByTestId('action-create_category').click();
    await expect(pageA.locator('[data-testid^="item-category-"]').filter({ hasText: 'Ops' })).toBeVisible({ timeout: 10_000 });

    await pageA.getByTestId('field-title').fill('Ship release');
    // The board is shared across every spec file in the suite, so the form's
    // default category (categories[0]) is not guaranteed to be the one just
    // created here — select it explicitly.
    await pageA.getByTestId('field-category_id').selectOption({ label: 'Ops' });
    await pageA.getByTestId('field-assignee').fill('alice');
    await pageA.getByTestId('action-create_task').click();
    const taskCardA = pageA.locator('[data-testid^="item-task-"]').filter({ hasText: 'Ship release' });
    await expect(taskCardA).toBeVisible({ timeout: 10_000 });

    // Both nodes must see the task on the active board before it's archived.
    const taskCardB = pageB.locator('[data-testid^="item-task-"]').filter({ hasText: 'Ship release' });
    await expect(taskCardB).toBeVisible({ timeout: 10_000 });

    await taskCardA.click();
    await pageA.getByTestId('action-complete_task').click();
    await pageA.getByTestId('action-archive_task').click();

    // Archiving moves the task out of the active board view for everyone.
    await expect(taskCardA).toBeHidden({ timeout: 10_000 });
    await expect(taskCardB).toBeHidden({ timeout: 10_000 });

    await ctxA.close();
    await ctxB.close();
  });
});
