// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team lead: mark a lead as Won or Lost and see a summary of closed deals`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a lead is marked Won or Lost, it moves out of the active pipeline and appears in a closed-deals summary visible to the whole team`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();

    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Team lead (node 0) adds a lead to close
      await pageA.getByRole('button', { name: '+ Add Lead' }).click();
      await expect(pageA.getByText('Add Lead')).toBeVisible({ timeout: 5_000 });
      await pageA.getByLabel('Lead / Contact Name').fill('E2E Win Lead');
      await pageA.getByLabel('Company').fill('Win Corp');
      await pageA.getByLabel('Estimated Deal Value ($)').fill('100000');
      await pageA.getByRole('button', { name: 'Add Lead' }).click();
      await expect(pageA.getByText('E2E Win Lead')).toBeVisible({ timeout: 5_000 });

      // Open the lead card's action menu and mark as Won
      await pageA.getByText('E2E Win Lead').click();
      await pageA.getByRole('button', { name: '✓ Mark as Won' }).click();

      // handleCloseLead auto-switches node A to the Closed Deals view
      // The lead appears in the closed-deals summary on node A
      await expect(pageA.getByRole('heading', { name: 'Closed Deals' })).toBeVisible({ timeout: 5_000 });
      await expect(pageA.getByText('E2E Win Lead')).toBeVisible({ timeout: 5_000 });
      await expect(pageA.getByText('✓ Won')).toBeVisible({ timeout: 5_000 });

      // Node 1 navigates to Closed Deals via the sidebar nav row
      await pageB.getByText('Closed Deals').first().click();
      await expect(pageB.getByRole('heading', { name: 'Closed Deals' })).toBeVisible({ timeout: 5_000 });

      // Closed lead is visible to the whole team within 5 s
      await expect(pageB.getByText('E2E Win Lead')).toBeVisible({ timeout: 5_000 });
      await expect(pageB.getByText('✓ Won')).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
