// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';
import { ensureBoard, mintInvite, openSecondMember } from './retro-helpers';

test.describe(`team member: mark an action item as done`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a member marks an action item done, it appears checked for everyone; only the author or facilitator can toggle the done state`, async ({ page, browser }) => {
    // A creates the retro (becomes the facilitator) and a teammate joins.
    await ensureBoard(page);
    const code = await mintInvite(page);
    const { ctx: ctxB, page: pageB } = await openSecondMember(browser, code, 1);

    // A adds an action item (the toggle control shows only for action-items the member owns).
    const text = 'Write the postmortem';
    await page.getByPlaceholder('Add to action items…').fill(text);
    await page.getByRole('button', { name: 'Add card' }).last().click();
    await expect(page.getByText(text)).toBeVisible({ timeout: 15_000 });

    // A (author + facilitator) marks it done.
    await page.getByRole('button', { name: 'Mark done' }).click();

    // It appears checked for everyone.
    await expect(page.getByText('✓ done')).toBeVisible({ timeout: 15_000 });
    await expect(pageB.getByText('✓ done')).toBeVisible({ timeout: 15_000 });

    // Only the author or facilitator can toggle: B (neither) has no toggle control.
    await expect(pageB.getByRole('button', { name: 'Mark not done' })).toHaveCount(0);
    await expect(pageB.getByRole('button', { name: 'Mark done' })).toHaveCount(0);

    await ctxB.close();
  });
});
