// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect, type Page } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, uniqueName } from './helpers';

// The e2e isolation harness pre-provisions one namespace + one context per
// spec file and binds every logged-in node to it as the group. A fresh
// member lands on the group's display-name gate before any content shows.
async function joinGroupIfNeeded(page: Page, name: string) {
  const gate = page.getByTestId('group-join-gate');
  try {
    await gate.waitFor({ state: 'visible', timeout: 15_000 });
  } catch {
    return;
  }
  await page.getByTestId('field-display_name').fill(name);
  await page.getByTestId('action-set_display_name').click();
  await gate.waitFor({ state: 'hidden', timeout: 10_000 });
}

test.describe(`member: pick exactly which people are part of a given expense`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test('only the members selected as participants on an expense are reflected in the balance calculation for that expense', async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const ctxC = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    const pageC = await ctxC.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);
      await loginViaHash(pageC, 2);
      await createWorkspace(pageA);
      await createWorkspace(pageB);
      await createWorkspace(pageC);

      const aliceName = uniqueName('alice');
      const bobName = uniqueName('bob');
      const carolName = uniqueName('carol');
      await joinGroupIfNeeded(pageA, aliceName);
      await joinGroupIfNeeded(pageB, bobName);
      await joinGroupIfNeeded(pageC, carolName);

      // Wait until A knows about all three members so it can deliberately
      // deselect Carol from the expense's participants.
      await expect(pageA.getByText(/3 members?/)).toBeVisible({ timeout: 15_000 });

      const description = uniqueName('groceries');
      await pageA.getByTestId('field-description').fill(description);
      await pageA.getByTestId('field-amount').fill('30');
      // All members are pre-selected as participants by default — deselect
      // Carol so only Alice and Bob share this particular cost.
      await pageA.getByTestId('field-participants').getByText(carolName, { exact: true }).click();
      await pageA.getByTestId('action-add_expense').click();

      // Carol was never a participant on this expense — her balance must be
      // untouched by it (still zero total owed).
      await pageC.getByTestId('tab-members').click();
      const carolRow = pageC.locator('[data-testid^="item-member-"]').filter({ hasText: carolName });
      await expect(carolRow).toContainText('owes ₹0', { timeout: 10_000 });

      // Bob WAS a participant — his share of the expense is reflected.
      await pageB.getByTestId('tab-members').click();
      const bobRow = pageB.locator('[data-testid^="item-member-"]').filter({ hasText: bobName });
      await expect(bobRow).toContainText('owes ₹15', { timeout: 10_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
      await ctxC.close();
    }
  });
});
