// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, inviteAndJoin } from './helpers';

test.describe(`team member: post my daily standup update — what I finished, what's blocking me, and what I plan to tackle next`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a team member submits a standup with done items, blockers, and planned items, every other member sees it on the dashboard within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Node A creates the shared workspace; Node B joins it via invite code.
      await createWorkspace(pageA);
      await inviteAndJoin(pageA, pageB);

      // Node A: the standup composer is already on the Dashboard tab (the
      // default tab) — no nav click needed, just fill and submit.
      // The board persists across the whole run, so give the content a unique
      // suffix — a bare literal like "Shipped login flow" could false-match a
      // leftover item from another test/story that shares a common prefix.
      const doneItems = `Shipped login flow ${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      await pageA.getByTestId('field-done_items').fill(doneItems);
      await pageA.getByTestId('field-blockers').fill('Waiting on API keys from infra');
      await pageA.getByTestId('field-planned_items').fill('Start dashboard layout');
      await pageA.getByTestId('field-date').fill('2025-01-15');
      await pageA.getByTestId('action-post_standup').click();

      // Node B: the submitted standup should appear on the dashboard within 5s
      await expect(
        pageB.getByTestId(/^item-standup-/).filter({ hasText: doneItems })
      ).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
