// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team member: post updates and comments on an active incident thread`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a member posts a comment on an incident, all other team members see it in the incident thread within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Node 0: create an incident and navigate to its detail
      await pageA.getByTestId('action-create_incident').click();
      await pageA.getByTestId('field-title').fill('Comment sync incident');
      await pageA.getByTestId('field-description').fill('Testing comment sync across nodes');
      await pageA.getByTestId('field-severity').fill('high');
      await pageA.getByTestId('action-create_incident').click();
      await pageA.getByTestId('item-incident').filter({ hasText: 'Comment sync incident' }).click();

      // Node 0: post a comment
      await pageA.getByTestId('field-body').fill('Restarted read replica 3, monitoring recovery');
      await pageA.getByTestId('action-add_comment').click();

      // Node 1: navigate to the same incident and see the comment within 5s
      await pageB.getByTestId('item-incident').filter({ hasText: 'Comment sync incident' }).click();
      await expect(
        pageB.getByTestId('item-comment').filter({ hasText: 'Restarted read replica 3, monitoring recovery' })
      ).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });

  test(`a member can edit or delete only their own comments; attempts on others' comments are rejected`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Node 0: create an incident and post a comment
      await pageA.getByTestId('action-create_incident').click();
      await pageA.getByTestId('field-title').fill('Ownership test incident');
      await pageA.getByTestId('field-description').fill('Testing comment ownership');
      await pageA.getByTestId('field-severity').fill('medium');
      await pageA.getByTestId('action-create_incident').click();
      await pageA.getByTestId('item-incident').filter({ hasText: 'Ownership test incident' }).click();
      await pageA.getByTestId('field-body').fill('Comment posted by node 0');
      await pageA.getByTestId('action-add_comment').click();
      await expect(
        pageA.getByTestId('item-comment').filter({ hasText: 'Comment posted by node 0' })
      ).toBeVisible({ timeout: 5_000 });

      // Node 1: sees the comment but should not have edit/delete controls for it
      await pageB.getByTestId('item-incident').filter({ hasText: 'Ownership test incident' }).click();
      const foreignComment = pageB.getByTestId('item-comment').filter({ hasText: 'Comment posted by node 0' });
      await expect(foreignComment).toBeVisible({ timeout: 5_000 });

      // Edit and delete controls must be absent for another user's comment
      await expect(foreignComment.getByTestId('action-edit_comment')).toBeHidden();
      await expect(foreignComment.getByTestId('action-delete_comment')).toBeHidden();
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
