// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team member: post a quick appreciation note naming a colleague`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a member posts a kudos, every other member sees it appear at the top of the feed within 2s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Node A posts kudos
      await pageA.getByPlaceholder('Who deserves kudos? (name or @handle)').fill('TestColleague');
      await pageA.getByPlaceholder('Why do they deserve it?').fill('Amazing work on the project');
      await pageA.getByRole('button', { name: '✨ Give kudos' }).click();

      // Node B sees it at the top of the feed within 2s
      await expect(pageB.getByText('🌟 TestColleague').first()).toBeVisible({ timeout: 2_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
