// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, inviteAndJoin, uniqueName } from './helpers';

test.describe(`responder: quickly report a new incident with a title, severity, and affected area`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a responder submits a new incident, every team member sees it appear in the incident list within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);
      // Put both nodes in ONE shared workspace so B can observe A's report.
      await inviteAndJoin(pageA, pageB);

      const title = uniqueName('incident');
      await pageA.getByTestId('field-title').fill(title);
      await pageA.getByTestId('field-description').fill('500s on checkout API');
      await pageA.getByTestId('field-severity').selectOption('Critical');
      await pageA.getByTestId('field-affected_area').fill('Payments');
      await pageA.getByTestId('action-create_incident').click();

      // A sees its own report immediately. It renders once in "Open
      // incidents" and once in "Recent activity" (same entity, two rows);
      // .first() just needs one to be visible.
      await expect(
        pageA.locator('[data-testid^="item-incident-"]').filter({ hasText: title }).first(),
      ).toBeVisible({ timeout: 5_000 });

      // B, a different team member, sees it appear within 5s without acting.
      await expect(
        pageB.locator('[data-testid^="item-incident-"]').filter({ hasText: title }).first(),
      ).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
