// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, uniqueName } from './helpers';

test.describe(`member: record that I paid someone back`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a member logs a settlement between two people, both members' balances update for everyone within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    await loginViaHash(pageA, 0);
    await loginViaHash(pageB, 1);
    await createWorkspace(pageA);
    await createWorkspace(pageB);

    const from = uniqueName('debtor');
    const to = uniqueName('creditor');

    // Establish a real debt first, so there is a balance worth settling.
    const addForm = pageA.getByTestId('add-expense-form');
    await addForm.getByTestId('field-description').fill(uniqueName('shared-cost'));
    await addForm.getByTestId('field-amount').fill('40');
    await pageA.getByTestId('field-paid_by').fill(to);
    await pageA.getByTestId('field-split_between').fill(`${to},${from}`);
    await pageA.getByTestId('action-add_expense').click();
    await expect(pageB.getByTestId(`item-balance-${from}`)).toContainText('owes', { timeout: 5_000 });

    // Node A logs a settlement of the full amount owed.
    const settleForm = pageA.getByTestId('settle-up-form');
    await settleForm.getByTestId('field-from').fill(from);
    await settleForm.getByTestId('field-to').fill(to);
    await settleForm.getByTestId('field-amount').fill('20');
    await pageA.getByTestId('action-record_settlement').click();

    // Both members' balances update for everyone (observed from node B).
    await expect(pageB.getByTestId(`item-balance-${from}`)).toContainText('settled up', { timeout: 5_000 });
    await expect(pageB.getByTestId(`item-balance-${to}`)).toContainText('settled up', { timeout: 5_000 });

    await ctxA.close();
    await ctxB.close();
  });
});
