// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect, type Page } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

/** Ensure node 0 has a workspace, creating one if the slate is blank. */
async function ensureWorkspace(page: Page): Promise<void> {
  const noWs = await page.getByText('No workspaces yet').isVisible({ timeout: 4_000 }).catch(() => false);
  if (noWs) {
    await page.getByRole('button', { name: 'Create workspace' }).first().click();
    await page.getByRole('dialog').getByRole('button', { name: 'Create workspace' }).click();
    await expect(page.getByText('Incident Dashboard')).toBeVisible({ timeout: 15_000 });
  }
}

/**
 * For multi-node tests: node 0 creates workspace + invite; node 1 joins.
 * Returns the invite code so the caller can pass it to node 1.
 */
async function setupWorkspaceAndInvite(pageA: Page, pageB: Page): Promise<void> {
  await loginViaHash(pageA, 0);
  await loginViaHash(pageB, 1);

  const noWsA = await pageA.getByText('No workspaces yet').isVisible({ timeout: 4_000 }).catch(() => false);
  if (noWsA) {
    await pageA.getByRole('button', { name: 'Create workspace' }).first().click();
    await pageA.getByRole('dialog').getByRole('button', { name: 'Create workspace' }).click();
    await expect(pageA.getByText('Incident Dashboard')).toBeVisible({ timeout: 15_000 });
  }

  const noWsB = await pageB.getByText('No workspaces yet').isVisible({ timeout: 4_000 }).catch(() => false);
  if (noWsB) {
    // Generate invite from node 0
    await pageA.getByRole('button', { name: '+ Invite' }).click();
    await pageA.getByRole('button', { name: 'Generate invite code' }).click();
    await expect(pageA.locator('label', { hasText: 'Invite code' })).toBeVisible({ timeout: 10_000 });
    const code = await pageA.locator('textarea').last().inputValue();
    await pageA.keyboard.press('Escape');

    // Node 1 joins
    await pageB.getByRole('button', { name: 'Join with invitation' }).click();
    await pageB.getByPlaceholder('Paste your invite code\u2026').fill(code);
    await pageB.getByRole('button', { name: 'Join workspace' }).click();
    await expect(pageB.getByText('Incident Dashboard')).toBeVisible({ timeout: 15_000 });
  }
}

test.describe(`on-call responder: report a new incident with a severity level and description`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await ensureWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a responder submits a new incident with a title, severity (P1\u2013P4), and description, every team member sees it appear on the dashboard within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();

    try {
      await setupWorkspaceAndInvite(pageA, pageB);

      const title = 'E2E-Report-CrossNode-Visible';

      // Node 0 reports the incident
      await pageA.getByRole('button', { name: '\u26a1 Report Incident' }).click();
      await pageA.getByRole('button', { name: 'P1' }).click();
      await pageA.getByPlaceholder('Brief incident title\u2026').fill(title);
      await pageA.getByPlaceholder('What is happening? Impact? Timeline?').fill('Production Postgres pool at 0 connections');
      await pageA.getByRole('button', { name: 'Report Incident' }).click();

      // Node 1 sees the incident appear on the dashboard within 5 s
      await expect(pageB.getByText(title)).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });

  test(`the incident starts in 'open' status with the reporter recorded`, async ({ page }) => {
    const title = 'E2E-Report-OpenStatus';

    // Report a new incident
    await page.getByRole('button', { name: '\u26a1 Report Incident' }).click();
    await page.getByRole('button', { name: 'P2' }).click();
    await page.getByPlaceholder('Brief incident title\u2026').fill(title);
    await page.getByPlaceholder('What is happening? Impact? Timeline?').fill('Test incident for status check');
    await page.getByRole('button', { name: 'Report Incident' }).click();

    // Incident card appears on dashboard
    await expect(page.getByText(title)).toBeVisible({ timeout: 10_000 });

    // Open the incident detail
    await page.getByText(title).first().click();

    // Status must be 'open'
    await expect(page.getByText('open')).toBeVisible({ timeout: 5_000 });
    // Reporter identity is recorded (ViewSub shows "reported by …")
    await expect(page.getByText(/reported by/i)).toBeVisible({ timeout: 5_000 });
  });
});
