// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect, type Page } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

async function ensureWorkspace(page: Page): Promise<void> {
  const noWs = await page.getByText('No workspaces yet').isVisible({ timeout: 4_000 }).catch(() => false);
  if (noWs) {
    await page.getByRole('button', { name: 'Create workspace' }).first().click();
    await page.getByRole('dialog').getByRole('button', { name: 'Create workspace' }).click();
    await expect(page.getByText('Incident Dashboard')).toBeVisible({ timeout: 15_000 });
  }
}

/** Report an incident, open its detail, acknowledge it, then resolve it. */
async function reportAckAndResolve(page: Page, title: string, rootCause: string): Promise<void> {
  // Report
  await page.getByRole('button', { name: '\u26a1 Report Incident' }).click();
  await page.getByRole('button', { name: 'P1' }).click();
  await page.getByPlaceholder('Brief incident title\u2026').fill(title);
  await page.getByPlaceholder('What is happening? Impact? Timeline?').fill('Resolve test');
  await page.getByRole('button', { name: 'Report Incident' }).click();
  await expect(page.getByText(title)).toBeVisible({ timeout: 10_000 });
  await page.getByText(title).first().click();

  // Acknowledge (required to unlock Resolve button)
  await page.getByRole('button', { name: 'Acknowledge' }).click();
  await expect(page.getByText('acknowledged')).toBeVisible({ timeout: 5_000 });

  // Resolve
  await page.getByRole('button', { name: 'Resolve' }).click();
  await expect(page.getByText('Resolve Incident')).toBeVisible({ timeout: 5_000 });
  await page.getByPlaceholder('What caused this incident?').fill(rootCause);
  await page.getByRole('button', { name: 'Mark Resolved' }).click();
}

test.describe(`incident commander: resolve an incident and tag a root cause`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await ensureWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after the commander resolves an incident with a root-cause tag, the status changes to 'resolved' and a resolved timestamp is recorded, visible to everyone`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();

    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);
      await ensureWorkspace(pageA);

      const noWsB = await pageB.getByText('No workspaces yet').isVisible({ timeout: 4_000 }).catch(() => false);
      if (noWsB) {
        await pageA.getByRole('button', { name: '+ Invite' }).click();
        await pageA.getByRole('button', { name: 'Generate invite code' }).click();
        await expect(pageA.locator('label', { hasText: 'Invite code' })).toBeVisible({ timeout: 10_000 });
        const code = await pageA.locator('textarea').last().inputValue();
        await pageA.keyboard.press('Escape');
        await pageB.getByRole('button', { name: 'Join with invitation' }).click();
        await pageB.getByPlaceholder('Paste your invite code\u2026').fill(code);
        await pageB.getByRole('button', { name: 'Join workspace' }).click();
        await expect(pageB.getByText('Incident Dashboard')).toBeVisible({ timeout: 15_000 });
      }

      const title = 'E2E-Resolve-CrossNode';
      const rootCause = 'connection leak in auth middleware';

      await reportAckAndResolve(pageA, title, rootCause);

      // Resolved box shows status + root cause on node 0
      await expect(pageA.getByText(/\u2705 Resolved/)).toBeVisible({ timeout: 5_000 });
      await expect(pageA.getByText(rootCause)).toBeVisible({ timeout: 5_000 });

      // Node 1 also sees 'resolved' status on the dashboard within 5 s
      await expect(pageB.getByText('resolved')).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });

  test(`no further status changes or escalations are allowed on a resolved incident`, async ({ page }) => {
    const title = 'E2E-Resolve-NoMoreActions';
    const rootCause = 'misconfigured load balancer';

    await reportAckAndResolve(page, title, rootCause);

    // Resolved box visible
    await expect(page.getByText(/\u2705 Resolved/)).toBeVisible({ timeout: 5_000 });

    // None of the action buttons (Acknowledge / Escalate / Resolve) are rendered
    // The ActionBar is hidden when isResolved = true (status === 'resolved')
    await expect(page.getByRole('button', { name: 'Acknowledge' })).toBeHidden({ timeout: 3_000 });
    await expect(page.getByRole('button', { name: 'Escalate' })).toBeHidden({ timeout: 3_000 });
    await expect(page.getByRole('button', { name: 'Resolve' })).toBeHidden({ timeout: 3_000 });
  });
});
