// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect, type Page } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

async function ensureWorkspace(page: Page): Promise<void> {
  const noWs = await page.getByText('No workspaces yet').isVisible({ timeout: 4_000 }).catch(() => false);
  if (noWs) {
    await page.getByRole('button', { name: 'Create workspace' }).first().click();
    await page.getByRole('dialog').getByRole('button', { name: 'Create workspace' }).click();
    await expect(page.getByText('Incident Dashboard')).toBeVisible({ timeout: 15_000 });
  }
}

async function quickReport(page: Page, title: string, severity: string): Promise<void> {
  await page.getByRole('button', { name: '\u26a1 Report Incident' }).click();
  await page.getByRole('button', { name: severity }).click();
  await page.getByPlaceholder('Brief incident title\u2026').fill(title);
  await page.getByPlaceholder('What is happening? Impact? Timeline?').fill('Dashboard sort test');
  await page.getByRole('button', { name: 'Report Incident' }).click();
  await expect(page.getByText(title)).toBeVisible({ timeout: 10_000 });
}

test.describe(`anyone on the team: see a dashboard of all open incidents sorted by severity`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await ensureWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`the dashboard always lists all incidents with open or acknowledged status, sorted P1 first through P4 last`, async ({ page }) => {
    const titleP3 = 'E2E-Dash-Sort-P3-Incident';
    const titleP1 = 'E2E-Dash-Sort-P1-Incident';

    // Create a P3 incident first, then a P1 incident
    await quickReport(page, titleP3, 'P3');
    await quickReport(page, titleP1, 'P1');

    // Both appear on the dashboard
    await expect(page.getByText(titleP1)).toBeVisible({ timeout: 5_000 });
    await expect(page.getByText(titleP3)).toBeVisible({ timeout: 5_000 });

    // P1 card must appear above the P3 card in the list (sorted by severity)
    const boxP1 = await page.getByText(titleP1).first().boundingBox();
    const boxP3 = await page.getByText(titleP3).first().boundingBox();
    if (boxP1 && boxP3) {
      expect(boxP1.y).toBeLessThan(boxP3.y);
    }

    // Both are visible in the default "Active" (open + acknowledged) filter
    await page.getByRole('button', { name: 'Active' }).click();
    await expect(page.getByText(titleP1)).toBeVisible({ timeout: 5_000 });
    await expect(page.getByText(titleP3)).toBeVisible({ timeout: 5_000 });
  });

  test(`resolved incidents are accessible via a separate 'past incidents' filter`, async ({ page }) => {
    // [Verifier] NOTE: The story expects a 'past incidents' filter label.
    // The UI exposes this as a 'Resolved' filter button (FilterBtn). Using that.
    const titleResolved = 'E2E-Dash-Resolved-Filter';

    // Create and resolve an incident
    await quickReport(page, titleResolved, 'P2');
    await page.getByText(titleResolved).first().click();
    await page.getByRole('button', { name: 'Acknowledge' }).click();
    await expect(page.getByText('acknowledged')).toBeVisible({ timeout: 5_000 });
    await page.getByRole('button', { name: 'Resolve' }).click();
    await page.getByPlaceholder('What caused this incident?').fill('Load spike — scaled up');
    await page.getByRole('button', { name: 'Mark Resolved' }).click();
    await expect(page.getByText(/\u2705 Resolved/)).toBeVisible({ timeout: 10_000 });

    // Go back to the dashboard
    await page.getByRole('button', { name: '\u2190 Back' }).click();

    // Default "Active" filter hides the resolved incident
    await expect(page.getByText(titleResolved)).toBeHidden({ timeout: 5_000 });

    // "Resolved" filter shows it
    await page.getByRole('button', { name: 'Resolved' }).click();
    await expect(page.getByText(titleResolved)).toBeVisible({ timeout: 5_000 });
  });
});
