// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`collaborator: see matching functions suggested as I start typing a formula`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test.skip(`after typing '=' followed by one or more letters, a dropdown appears listing all functions whose names start with those letters`, async ({ page: _page }) => {
    // TODO: verifier-writer turns this skip into a real assertion using selectors
    // from the frontend the frontend-writer produced.
  });

  test.skip(`selecting a suggestion from the dropdown inserts the function name and opening parenthesis into the cell`, async ({ page: _page }) => {
    // TODO: verifier-writer turns this skip into a real assertion using selectors
    // from the frontend the frontend-writer produced.
  });

  test.skip(`the dropdown disappears when the user clears the formula bar or presses Escape`, async ({ page: _page }) => {
    // TODO: verifier-writer turns this skip into a real assertion using selectors
    // from the frontend the frontend-writer produced.
  });
});
