// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`collaborator: see each person's selected cell highlighted in their unique color`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`when a collaborator selects a cell, every other collaborator sees that cell highlighted in that person's assigned color within 1s`, async ({ browser }) => {
    // Multi-node: node 0 clicks a cell; node 1 must see a cursor highlight appear within 1s.
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Node 0 selects cell (row 2, col 3) — triggers update_cursor
      await pageA.getByTestId('item-Cell-2-3').click();

      // Node 1 sees the cursor highlight from node 0 within 1s
      await expect(pageB.getByTestId('item-Cursor')).toBeVisible({ timeout: 1_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });

  test(`each connected user is assigned a distinct color that persists for the duration of their session`, async ({ browser }) => {
    // Multi-node: both users select cells; on node 0's view, two distinct cursor colors appear.
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Both users select cells to emit cursor updates
      await pageA.getByTestId('item-Cell-0-0').click();
      await pageB.getByTestId('item-Cell-1-0').click();

      // Node 0's view should show two cursor elements with distinct colors
      // [Verifier] NOTE: Cursor color exposed via data-color attribute (derived from Cursor.color field)
      const cursorsOnA = pageA.getByTestId('item-Cursor');
      await expect(cursorsOnA.first()).toBeVisible({ timeout: 5_000 });
      await expect(cursorsOnA.nth(1)).toBeVisible({ timeout: 5_000 });

      const colorFirst = await cursorsOnA.first().getAttribute('data-color');
      const colorSecond = await cursorsOnA.nth(1).getAttribute('data-color');
      expect(colorFirst).toBeTruthy();
      expect(colorSecond).toBeTruthy();
      expect(colorFirst).not.toEqual(colorSecond);
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });

  test(`when a user disconnects, their cursor highlight disappears for everyone`, async ({ browser }) => {
    // Multi-node: node 0 sets cursor; then removes it (simulating disconnect); node 1 sees it vanish.
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Node 0 selects a cell so its cursor appears on node 1
      await pageA.getByTestId('item-Cell-0-0').click();
      await expect(pageB.getByTestId('item-Cursor')).toBeVisible({ timeout: 5_000 });

      // Node 0 disconnects by removing its cursor (remove_cursor is called on disconnect)
      await pageA.getByTestId('action-remove_cursor').click();

      // Node 1 no longer sees node 0's cursor highlight
      await expect(pageB.getByTestId('item-Cursor')).toBeHidden({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
