// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect, type Page, type Locator } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, uniqueName } from './helpers';

// The e2e isolation harness pre-provisions one namespace + one context per
// spec file and binds every logged-in node to it as the group. A fresh
// member lands on the group's display-name gate before any content shows.
async function joinGroupIfNeeded(page: Page, name: string) {
  const gate = page.getByTestId('group-join-gate');
  try {
    await gate.waitFor({ state: 'visible', timeout: 15_000 });
  } catch {
    return;
  }
  await page.getByTestId('field-display_name').fill(name);
  await page.getByTestId('action-set_display_name').click();
  await gate.waitFor({ state: 'hidden', timeout: 10_000 });
}

// The Dashboard's "Balances (net)" row has no data-testid (BalRow), but each
// row is a `<span class="name">` + `<span class="val">` pair — locate the row
// by its member name and read the net value next to it.
function netBalanceValue(page: Page, memberName: string): Locator {
  return page.locator(`xpath=//span[@class="name" and normalize-space(text())="${memberName}"]/..`).locator('.val');
}

test.describe(`anyone in the group: see a live balance of who owes whom`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`the balances view always reflects the sum of all expenses' splits minus any recorded settlements, updating live as data changes`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);
      await createWorkspace(pageA);
      await createWorkspace(pageB);

      const aliceName = uniqueName('alice');
      const bobName = uniqueName('bob');
      await joinGroupIfNeeded(pageA, aliceName);
      await joinGroupIfNeeded(pageB, bobName);

      await expect(pageA.getByText(/2 members?/)).toBeVisible({ timeout: 15_000 });

      // Alice pays 20, split equally with Bob — she's owed 10, he owes 10.
      const description = uniqueName('taxi');
      await pageA.getByTestId('field-description').fill(description);
      await pageA.getByTestId('field-amount').fill('20');
      await pageA.getByTestId('action-add_expense').click();

      await pageA.getByTestId('tab-dashboard').click();
      await expect(netBalanceValue(pageA, aliceName)).toHaveText('+₹10', { timeout: 10_000 });
      await expect(netBalanceValue(pageA, bobName)).toHaveText('-₹10', { timeout: 10_000 });

      // Bob repays Alice the full 10 he owes — the live view updates to
      // reflect the split minus the settlement, with no page reload.
      await pageA.getByTestId('open-settle-btn').click();
      await pageA.getByTestId('field-from').selectOption({ label: bobName });
      await pageA.getByTestId('field-to').selectOption({ label: aliceName });
      await pageA.getByTestId('field-amount').fill('10');
      await pageA.getByTestId('action-record_settlement').click();

      await expect(netBalanceValue(pageA, aliceName)).toHaveText('+₹0', { timeout: 10_000 });
      await expect(netBalanceValue(pageA, bobName)).toHaveText('+₹0', { timeout: 10_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
