// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`anyone on the team: see all kudos posted so far, with author and timestamp`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`the feed displays every kudos, newest first, with the poster's name and exact post time`, async ({ page }) => {
    // Post Alice first, then Bob — Bob should appear at the top (newest first)
    await page.getByPlaceholder('Who deserves kudos? (name or @handle)').fill('Alice');
    await page.getByPlaceholder('Why do they deserve it?').fill('Great job on the release');
    await page.getByRole('button', { name: '✨ Give kudos' }).click();
    await expect(page.getByText('🌟 Alice')).toBeVisible({ timeout: 5_000 });

    await page.getByPlaceholder('Who deserves kudos? (name or @handle)').fill('Bob');
    await page.getByPlaceholder('Why do they deserve it?').fill('Excellent presentation today');
    await page.getByRole('button', { name: '✨ Give kudos' }).click();
    await expect(page.getByText('🌟 Bob')).toBeVisible({ timeout: 5_000 });

    // Newest first: Bob's card should appear before Alice's in the DOM
    const recipients = page.locator('text=/^🌟 /');
    await expect(recipients.nth(0)).toContainText('Bob');
    await expect(recipients.nth(1)).toContainText('Alice');

    // Poster's name shown — own kudos show "you" in the From line
    await expect(page.getByText('you').first()).toBeVisible();

    // Timestamp present — toLocaleString produces a non-empty date/time string
    await expect(page.getByText(/From/).first()).toBeVisible();
  });

  test(`the feed updates live as new kudos arrive`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // A posts a new kudos
      await pageA.getByPlaceholder('Who deserves kudos? (name or @handle)').fill('LiveUpdateUser');
      await pageA.getByPlaceholder('Why do they deserve it?').fill('Brilliant solution');
      await pageA.getByRole('button', { name: '✨ Give kudos' }).click();

      // B's feed updates live via subscription — no manual refresh
      await expect(pageB.getByText('🌟 LiveUpdateUser').first()).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
