// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`anyone on the team: see all current tasks and their status at a glance`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`the task list always displays every task with its current status (open or completed), sorted by status and creation time`, async ({ page }) => {
    // The view groups tasks under OPEN and COMPLETED section headings.
    // Create one task → verify it appears under OPEN.
    // Complete it → verify it moves to COMPLETED and OPEN decrements.

    await page.getByPlaceholder('Add a new task…').fill('Write tests');
    await page.getByRole('button', { name: '+ Add' }).click();

    // Task is visible and the OPEN section header appears.
    await expect(page.getByText('Write tests')).toBeVisible({ timeout: 5_000 });
    await expect(page.getByText(/OPEN/)).toBeVisible({ timeout: 5_000 });

    // Add a second task so we can observe mixed statuses.
    await page.getByPlaceholder('Add a new task…').fill('Review PR');
    await page.getByRole('button', { name: '+ Add' }).click();
    await expect(page.getByText('Review PR')).toBeVisible({ timeout: 5_000 });

    // Complete the first task via its checkbox button.
    await page.getByTitle('Mark as complete').first().click();

    // Both section headers must now be visible simultaneously.
    await expect(page.getByText(/OPEN/)).toBeVisible({ timeout: 5_000 });
    await expect(page.getByText(/COMPLETED/)).toBeVisible({ timeout: 5_000 });

    // Both tasks must still be visible (one open, one completed).
    await expect(page.getByText('Write tests')).toBeVisible({ timeout: 5_000 });
    await expect(page.getByText('Review PR')).toBeVisible({ timeout: 5_000 });
  });
});
