// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`anyone on the team: see a live dashboard of all open incidents sorted by severity`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`the dashboard always shows all open and acknowledged incidents ordered by severity (critical first), refreshing live as statuses change`, async ({ page }) => {
    // Create three incidents with distinct severities in non-priority order
    const incidents: Array<[string, string]> = [
      ['Medium severity incident', 'medium'],
      ['Critical severity incident', 'critical'],
      ['High severity incident', 'high'],
    ];
    for (const [title, severity] of incidents) {
      await page.getByTestId('action-create_incident').click();
      await page.getByTestId('field-title').fill(title);
      await page.getByTestId('field-description').fill(`Testing ${severity} ordering`);
      await page.getByTestId('field-severity').fill(severity);
      await page.getByTestId('action-create_incident').click();
      await expect(page.getByTestId('item-incident').filter({ hasText: title })).toBeVisible({ timeout: 5_000 });
    }

    // Collect the rendered order and verify critical appears before medium
    const allItems = await page.getByTestId('item-incident').all();
    const texts = await Promise.all(allItems.map((item) => item.textContent()));
    const criticalIdx = texts.findIndex((t) => t?.includes('Critical severity incident'));
    const mediumIdx = texts.findIndex((t) => t?.includes('Medium severity incident'));
    expect(criticalIdx).toBeGreaterThanOrEqual(0);
    expect(mediumIdx).toBeGreaterThanOrEqual(0);
    expect(criticalIdx).toBeLessThan(mediumIdx);
  });

  test(`resolved incidents are accessible in a separate history view`, async ({ page }) => {
    // Create an incident
    await page.getByTestId('action-create_incident').click();
    await page.getByTestId('field-title').fill('History view incident');
    await page.getByTestId('field-description').fill('Testing resolved incident in history');
    await page.getByTestId('field-severity').fill('low');
    await page.getByTestId('action-create_incident').click();

    // Resolve the incident
    await page.getByTestId('item-incident').filter({ hasText: 'History view incident' }).click();
    await page.getByTestId('action-resolve_incident').click();

    // Navigate to the history view and verify the resolved incident is listed there
    await page.getByRole('link', { name: /history/i }).click();
    await expect(
      page.getByTestId('item-incident').filter({ hasText: 'History view incident' })
    ).toBeVisible({ timeout: 5_000 });
  });
});
