// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team member: see all documents tagged with a specific keyword`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`when a member clicks a tag, the view updates to show only documents with that tag, filtering live as the graph changes`, async ({ page }) => {
    // Create a document and add a tag to it
    await page.getByRole('button', { name: '+ New' }).click();
    await page.getByPlaceholder('Document title…').fill('Tagged Doc');
    await page.getByRole('button', { name: 'Create' }).click();
    await expect(page.getByPlaceholder('add tag…')).toBeVisible({ timeout: 10_000 });

    await page.getByPlaceholder('add tag…').fill('machine-learning');
    await page.getByRole('button', { name: '+' }).click();
    await expect(page.getByText('#machine-learning')).toBeVisible({ timeout: 10_000 });

    // Switch to Tags view via the sidebar view switcher
    await page.getByRole('button', { name: 'Tags' }).click();

    // Click the '#machine-learning' tag button inside TagFilterView
    // The button text is '#machine-learning' followed by a count badge
    await page.getByRole('button', { name: /#machine-learning/ }).click();

    // The heading updates to show the active tag filter
    await expect(page.getByText('Documents tagged #machine-learning')).toBeVisible({ timeout: 5_000 });

    // The tagged document appears in the filtered list
    await expect(page.getByText('Tagged Doc')).toBeVisible({ timeout: 5_000 });
  });
});
