// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, uniqueName } from './helpers';

test.describe(`household member: see who added each login`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`every entry displayed in the vault shows the name of the member who added it`, async ({ page }) => {
    const serviceName = uniqueName('service');
    await page.getByTestId('field-service_name').fill(serviceName);
    await page.getByTestId('field-username').fill('family@home.com');
    await page.getByTestId('field-secret').fill('s3cr3t!');
    await page.getByTestId('action-add_entry').click();

    const row = page.locator('[data-testid^="item-vaultentry-"]').filter({ hasText: serviceName });
    await expect(row).toBeVisible({ timeout: 10_000 });

    // The entry shows who added it — the "Added by" byline naming the author,
    // marked "(you)" since this member is the one who just added it.
    await expect(row.getByText('Added by', { exact: false })).toBeVisible();
    await expect(row.getByText('(you)', { exact: false })).toBeVisible();
  });
});
