// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, uniqueName } from './helpers';

test.describe(`member: see a running balance of who owes whom`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`the balances view always reflects the sum of expenses minus settlements for every member, live`, async ({ page }) => {
    await createWorkspace(page);

    const payer = uniqueName('payer');
    const other = uniqueName('other');

    const addForm = page.getByTestId('add-expense-form');
    await addForm.getByTestId('field-description').fill(uniqueName('dinner'));
    await addForm.getByTestId('field-amount').fill('100');
    await page.getByTestId('field-paid_by').fill(payer);
    await page.getByTestId('field-split_between').fill(`${payer},${other}`);
    await page.getByTestId('action-add_expense').click();

    // Split evenly between two members: payer is owed half, other owes half.
    await expect(page.getByTestId(`item-balance-${payer}`)).toContainText('is owed', { timeout: 10_000 });
    await expect(page.getByTestId(`item-balance-${other}`)).toContainText('owes', { timeout: 10_000 });

    // Settling the debt in full brings both balances back to zero, live —
    // no reload, same page.
    const settleForm = page.getByTestId('settle-up-form');
    await settleForm.getByTestId('field-from').fill(other);
    await settleForm.getByTestId('field-to').fill(payer);
    await settleForm.getByTestId('field-amount').fill('50');
    await page.getByTestId('action-record_settlement').click();

    await expect(page.getByTestId(`item-balance-${payer}`)).toContainText('settled up', { timeout: 10_000 });
    await expect(page.getByTestId(`item-balance-${other}`)).toContainText('settled up', { timeout: 10_000 });
  });
});
