// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`collaborator: see each person's selected cell highlighted in their unique color`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test.skip(`when a collaborator selects a cell, every other collaborator sees that cell highlighted in that person's assigned color within 1s`, async ({ page: _page }) => {
    // TODO: verifier-writer turns this skip into a real assertion using selectors
    // from the frontend the frontend-writer produced.
  });

  test.skip(`each connected user is assigned a distinct color that persists for the duration of their session`, async ({ page: _page }) => {
    // TODO: verifier-writer turns this skip into a real assertion using selectors
    // from the frontend the frontend-writer produced.
  });

  test.skip(`when a user disconnects, their cursor highlight disappears for everyone`, async ({ page: _page }) => {
    // TODO: verifier-writer turns this skip into a real assertion using selectors
    // from the frontend the frontend-writer produced.
  });
});
