// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`collaborator: see matching functions suggested as I start typing a formula`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after typing '=' followed by one or more letters, a dropdown appears listing all functions whose names start with those letters`, async ({ page }) => {
    // Select a cell, type '=SU' in the formula bar — a dropdown with SUM must appear.
    await page.getByTestId('item-Cell-0-0').click();
    await page.getByTestId('field-formula').fill('=SU');

    // A dropdown listing functions starting with 'SU' (e.g. SUM) should appear
    await expect(page.getByTestId('item-FunctionDef').filter({ hasText: 'SUM' })).toBeVisible({ timeout: 3_000 });
  });

  test(`selecting a suggestion from the dropdown inserts the function name and opening parenthesis into the cell`, async ({ page }) => {
    // Type '=SU', wait for dropdown, click SUM suggestion — formula bar should contain 'SUM('.
    await page.getByTestId('item-Cell-0-0').click();
    await page.getByTestId('field-formula').fill('=SU');

    const suggestion = page.getByTestId('item-FunctionDef').filter({ hasText: 'SUM' });
    await expect(suggestion).toBeVisible({ timeout: 3_000 });
    await suggestion.click();

    // The formula bar now contains 'SUM(' (function name + opening parenthesis)
    await expect(page.getByTestId('field-formula')).toHaveValue(/SUM\(/);
  });

  test(`the dropdown disappears when the user clears the formula bar or presses Escape`, async ({ page }) => {
    // Type '=SU' to trigger the autocomplete dropdown, then press Escape to dismiss it.
    await page.getByTestId('item-Cell-0-0').click();
    await page.getByTestId('field-formula').fill('=SU');

    // Verify dropdown is visible first
    await expect(page.getByTestId('item-FunctionDef')).toBeVisible({ timeout: 3_000 });

    // Press Escape — the dropdown must disappear
    await page.keyboard.press('Escape');
    await expect(page.getByTestId('item-FunctionDef')).toBeHidden({ timeout: 2_000 });
  });
});
