// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, uniqueName, createWorkspace } from './helpers';

// Minimal 1x1 transparent PNG, used to fill the mockup upload's file input.
const PNG_1x1 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
  'base64',
);

test.describe(`anyone reviewing: see the timestamp on every pin`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`every pin always displays the time it was created, ordered oldest to newest`, async ({ page }) => {
    await createWorkspace(page);

    const title = uniqueName('mockup');
    await page.getByTestId('field-title').fill(title);
    await page.getByTestId('field-image').setInputFiles({
      name: 'mockup.png',
      mimeType: 'image/png',
      buffer: PNG_1x1,
    });
    await page.getByTestId('action-upload_mockup').click();
    await expect(page.getByTestId('item-mockup').filter({ hasText: title })).toBeVisible({ timeout: 10_000 });

    const img = page.locator('img').first();
    await img.waitFor({ state: 'visible', timeout: 10_000 });
    const frame = img.locator('xpath=..');

    const firstText = uniqueName('pin-first');
    await frame.click({ position: { x: 30, y: 30 } });
    await page.getByTestId('field-text').fill(firstText);
    await page.getByTestId('action-add_pin').click();
    await expect(page.getByTestId('item-pin').filter({ hasText: firstText })).toBeVisible({ timeout: 10_000 });

    const secondText = uniqueName('pin-second');
    await frame.click({ position: { x: 70, y: 70 } });
    await page.getByTestId('field-text').fill(secondText);
    await page.getByTestId('action-add_pin').click();
    await expect(page.getByTestId('item-pin').filter({ hasText: secondText })).toBeVisible({ timeout: 10_000 });

    const rows = page.getByTestId('item-pin');
    const firstRow = rows.filter({ hasText: firstText });
    const secondRow = rows.filter({ hasText: secondText });

    // Every pin always displays the time it was created.
    await expect(firstRow.locator('time')).not.toHaveText('');
    await expect(secondRow.locator('time')).not.toHaveText('');

    // Ordered oldest to newest: the first-created pin renders before the
    // second-created pin in the list.
    const allTexts = await rows.allTextContents();
    const firstIdx = allTexts.findIndex((t) => t.includes(firstText));
    const secondIdx = allTexts.findIndex((t) => t.includes(secondText));
    expect(firstIdx).toBeGreaterThanOrEqual(0);
    expect(secondIdx).toBeGreaterThanOrEqual(0);
    expect(firstIdx).toBeLessThan(secondIdx);
  });
});
