// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`collaborator: type values or formulas into any cell`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a collaborator sets a cell value, all other collaborators see the new value in the same cell within 2s`, async ({ browser }) => {
    // Multi-node: node 0 sets A1=1500; node 1 must see it within 2s.
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Node 0 selects cell A1 (row 0, col 0) and sets a value
      await pageA.getByTestId('item-Cell-0-0').click();
      await pageA.getByTestId('field-raw_value').fill('1500');
      await pageA.getByTestId('action-set_cell').click();

      // Node 1 sees the new value in the same cell within 2s
      await expect(pageB.getByTestId('item-Cell-0-0')).toContainText('1500', { timeout: 2_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });

  test(`entering a formula (e.g. =SUM(A1:A5)) stores the raw formula and displays the computed result for everyone`, async ({ browser }) => {
    // Multi-node: node 0 fills A1:A5 with 10, sets =SUM(A1:A5) in A6; both nodes see 50.
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Set source values in A1–A5 (rows 0–4, col 0)
      for (let row = 0; row < 5; row++) {
        await pageA.getByTestId(`item-Cell-${row}-0`).click();
        await pageA.getByTestId('field-raw_value').fill('10');
        await pageA.getByTestId('action-set_cell').click();
      }

      // Enter formula =SUM(A1:A5) in A6 (row 5, col 0)
      await pageA.getByTestId('item-Cell-5-0').click();
      await pageA.getByTestId('field-formula').fill('=SUM(A1:A5)');
      await pageA.getByTestId('action-set_cell_formula').click();

      // The formula cell displays the computed result (50) for all collaborators
      await expect(pageA.getByTestId('item-Cell-5-0')).toContainText('50', { timeout: 5_000 });
      await expect(pageB.getByTestId('item-Cell-5-0')).toContainText('50', { timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
