// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, inviteAndJoin } from './helpers';

// Fresh 2-node game: pageA is white (node 0, host), pageB is black (node 1).
async function startNewGame(pageA: import('@playwright/test').Page, pageB: import('@playwright/test').Page) {
  await inviteAndJoin(pageA, pageB);
  await expect(pageA.getByTestId('action-create_game')).toBeVisible({ timeout: 15_000 });
  await pageA.getByTestId('action-create_game').click();
  await expect(pageA.getByTestId('chess-board')).toBeVisible({ timeout: 5_000 });
  await expect(pageB.getByTestId('chess-board')).toBeVisible({ timeout: 5_000 });
}

test.describe(`player: undo my previewed move before submitting it`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`a player can undo their previewed move any number of times before submitting, with no effect on shared game state`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    await loginViaHash(pageA, 0);
    await loginViaHash(pageB, 1);
    await startNewGame(pageA, pageB);

    // First preview + undo cycle.
    await pageA.getByTestId('square-e2').click();
    await pageA.getByTestId('square-e4').click();
    await expect(pageA.getByTestId('square-e4')).toContainText('♙');
    await pageA.getByTestId('undo-move-btn').click();
    await expect(pageA.getByTestId('square-e2')).toContainText('♙');
    await expect(pageA.getByTestId('square-e4')).not.toContainText('♙');

    // A second, different preview + undo cycle — "any number of times".
    await pageA.getByTestId('square-e2').click();
    await pageA.getByTestId('square-e3').click();
    await expect(pageA.getByTestId('square-e3')).toContainText('♙');
    await pageA.getByTestId('undo-move-btn').click();
    await expect(pageA.getByTestId('square-e2')).toContainText('♙');
    await expect(pageA.getByTestId('square-e3')).not.toContainText('♙');

    // Neither preview/undo cycle ever touched shared game state — the
    // opponent still sees the original starting position.
    await expect(pageB.getByTestId('square-e2')).toContainText('♙');
    await expect(pageB.getByTestId('square-e3')).not.toContainText('♙');
    await expect(pageB.getByTestId('square-e4')).not.toContainText('♙');

    await ctxA.close();
    await ctxB.close();
  });

  test(`once a move is submitted it is permanent and can no longer be undone`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    await loginViaHash(pageA, 0);
    await loginViaHash(pageB, 1);
    await startNewGame(pageA, pageB);

    await pageA.getByTestId('square-e2').click();
    await pageA.getByTestId('square-e4').click();
    await pageA.getByTestId('action-submit_move').click();

    // The move commits and syncs to the opponent within 5s.
    await expect(pageA.getByTestId('square-e4')).toContainText('♙', { timeout: 5_000 });
    await expect(pageB.getByTestId('square-e4')).toContainText('♙', { timeout: 5_000 });

    // The preview/undo cycle resets once the move is committed — there is
    // nothing left to undo, so the control is disabled.
    await expect(pageA.getByTestId('undo-move-btn')).toBeDisabled();

    await ctxA.close();
    await ctxB.close();
  });
});
