// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, uniqueName, inviteAndJoin } from './helpers';

// Minimal 1x1 transparent PNG, used to fill the mockup upload's file input.
const PNG_1x1 = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
  'base64',
);

test.describe(`designer: upload a new mockup version`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after the designer uploads a mockup, every teammate sees it appear within 5s`, async ({ browser }) => {
    const ctxDesigner = await browser.newContext();
    const ctxTeammate = await browser.newContext();
    const designer = await ctxDesigner.newPage();
    const teammate = await ctxTeammate.newPage();
    await loginViaHash(designer, 0);
    await loginViaHash(teammate, 1);

    // Put both nodes in one shared workspace before the designer uploads.
    await inviteAndJoin(designer, teammate);

    const title = uniqueName('mockup');
    await designer.getByTestId('field-title').fill(title);
    await designer.getByTestId('field-image').setInputFiles({
      name: 'mockup.png',
      mimeType: 'image/png',
      buffer: PNG_1x1,
    });
    await designer.getByTestId('action-upload_mockup').click();

    // Designer sees their own upload.
    await expect(designer.getByTestId('item-mockup').filter({ hasText: title })).toBeVisible({ timeout: 10_000 });

    // Every teammate sees it appear within 5s.
    await expect(teammate.getByTestId('item-mockup').filter({ hasText: title })).toBeVisible({ timeout: 5_000 });

    await ctxDesigner.close();
    await ctxTeammate.close();
  });
});
