// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';
import { ensureBoard, mintInvite, openSecondMember } from './retro-helpers';

test.describe(`team member: upvote cards others wrote`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a member upvotes a card, the vote count increases for everyone within 5s; a member can upvote the same card only once`, async ({ page, browser }) => {
    await ensureBoard(page);
    const code = await mintInvite(page);
    const { ctx: ctxB, page: pageB } = await openSecondMember(browser, code, 1);

    // A adds a card; B upvotes it.
    const text = 'Shipped on time';
    await page.getByPlaceholder('Add to went well…').fill(text);
    await page.getByRole('button', { name: 'Add card' }).first().click();
    await expect(pageB.getByText(text)).toBeVisible({ timeout: 15_000 });
    const upvoteB = pageB.getByRole('button', { name: 'Upvote' }).first();
    await upvoteB.click();

    // The vote count increases for everyone (A sees ▲ 1) within ~5s.
    await expect(page.getByRole('button', { name: 'Upvote' }).first()).toContainText('1', {
      timeout: 15_000,
    });

    // A member can upvote the same card only once — B's vote button is now disabled.
    await expect(upvoteB).toBeDisabled({ timeout: 15_000 });

    await ctxB.close();
  });
});
