// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`collaborator: use formulas like SUM, AVERAGE, MIN, MAX, COUNT, and IF that reference other cells`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`a cell containing =SUM(B1:B10) displays the correct sum of those cells' numeric values`, async ({ page }) => {
    // Set B1–B10 (col 1, rows 0–9) each to 5; sum should be 50.
    for (let row = 0; row < 10; row++) {
      await page.getByTestId(`item-Cell-${row}-1`).click();
      await page.getByTestId('field-raw_value').fill('5');
      await page.getByTestId('action-set_cell').click();
    }

    // Set formula =SUM(B1:B10) in B11 (row 10, col 1)
    await page.getByTestId('item-Cell-10-1').click();
    await page.getByTestId('field-formula').fill('=SUM(B1:B10)');
    await page.getByTestId('action-set_cell_formula').click();

    // The computed result (50) is displayed in B11
    await expect(page.getByTestId('item-Cell-10-1')).toContainText('50', { timeout: 5_000 });
  });

  test(`when a referenced cell's value changes, every formula that depends on it recalculates and all collaborators see the new result`, async ({ browser }) => {
    // Multi-node: node 0 sets A1=10, formula A2=SUM(A1:A1)=10; updates A1=20; both see A2=20.
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Set A1 = 10 (row 0, col 0)
      await pageA.getByTestId('item-Cell-0-0').click();
      await pageA.getByTestId('field-raw_value').fill('10');
      await pageA.getByTestId('action-set_cell').click();

      // Set formula =SUM(A1:A1) in A2 (row 1, col 0)
      await pageA.getByTestId('item-Cell-1-0').click();
      await pageA.getByTestId('field-formula').fill('=SUM(A1:A1)');
      await pageA.getByTestId('action-set_cell_formula').click();

      // Both nodes see the initial computed result of 10
      await expect(pageA.getByTestId('item-Cell-1-0')).toContainText('10', { timeout: 5_000 });
      await expect(pageB.getByTestId('item-Cell-1-0')).toContainText('10', { timeout: 5_000 });

      // Update A1 to 20 — the formula must recalculate
      await pageA.getByTestId('item-Cell-0-0').click();
      await pageA.getByTestId('field-raw_value').fill('20');
      await pageA.getByTestId('action-set_cell').click();

      // Both collaborators see the updated formula result of 20
      await expect(pageA.getByTestId('item-Cell-1-0')).toContainText('20', { timeout: 5_000 });
      await expect(pageB.getByTestId('item-Cell-1-0')).toContainText('20', { timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
