// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

test.describe(`team lead: write a postmortem after an incident is resolved — with a timeline, root cause, and action items`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`a postmortem can only be created for incidents with status 'resolved'`, async ({ page }) => {
    // Create an incident (status: open)
    await page.getByTestId('action-create_incident').click();
    await page.getByTestId('field-title').fill('Open incident postmortem gate');
    await page.getByTestId('field-description').fill('Verifying postmortem is gated on resolved status');
    await page.getByTestId('field-severity').fill('medium');
    await page.getByTestId('action-create_incident').click();

    // Navigate to the open incident — create_postmortem must not be available
    await page.getByTestId('item-incident').filter({ hasText: 'Open incident postmortem gate' }).click();
    await expect(page.getByTestId('action-create_postmortem')).toBeHidden({ timeout: 3_000 });
  });

  test(`after the lead publishes a postmortem, every team member can view it linked to the incident`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);

      // Node 0: create an incident, resolve it, then write a postmortem
      await pageA.getByTestId('action-create_incident').click();
      await pageA.getByTestId('field-title').fill('Resolved incident for postmortem');
      await pageA.getByTestId('field-description').fill('Testing postmortem visibility');
      await pageA.getByTestId('field-severity').fill('critical');
      await pageA.getByTestId('action-create_incident').click();

      await pageA.getByTestId('item-incident').filter({ hasText: 'Resolved incident for postmortem' }).click();
      await pageA.getByTestId('action-resolve_incident').click();

      // Write and publish the postmortem
      await pageA.getByTestId('action-create_postmortem').click();
      await pageA.getByTestId('field-timeline').fill('14:32 alerts fired → 14:45 ack → 15:10 resolved');
      await pageA.getByTestId('field-root_cause').fill('Connection pool max was set to 50, needed 200 under load');
      await pageA.getByTestId('field-action_items').fill('Increase pool max to 200; add pool-size alerting');
      await pageA.getByTestId('action-create_postmortem').click();

      // Node 1: navigate to the resolved incident (via history) and see the postmortem
      await pageB.getByRole('link', { name: /history/i }).click();
      await pageB.getByTestId('item-incident').filter({ hasText: 'Resolved incident for postmortem' }).click();
      await expect(pageB.getByTestId('item-postmortem')).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
