// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, inviteAndJoin, uniqueName } from './helpers';

test.describe(`incident commander: write up a postmortem once an incident is resolved, covering summary, root cause, and action items`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`a postmortem can be saved as a draft, then marked published`, async ({ page }) => {
    const title = uniqueName('incident');
    await page.getByTestId('field-title').fill(title);
    await page.getByTestId('field-description').fill('500s on checkout API');
    await page.getByTestId('field-severity').selectOption('Critical');
    await page.getByTestId('field-affected_area').fill('Payments');
    await page.getByTestId('action-create_incident').click();
    await page.locator('[data-testid^="item-incident-"]').filter({ hasText: title }).click();

    const incidentId = page.url().split('/incidents/')[1];
    expect(incidentId).toBeTruthy();

    await page.getByRole('link', { name: 'Postmortems' }).click();

    const summary = uniqueName('postmortem');
    await page.getByTestId('field-incident_id').fill(incidentId);
    await page.getByTestId('field-summary').fill(summary);
    await page.getByTestId('field-root_cause').fill('Bad deploy');
    await page.getByTestId('field-resolution_steps').fill('Rolled back');
    await page.getByTestId('field-lessons_learned').fill('Add canary tests');
    await page.getByTestId('action-create_postmortem').click();

    const card = page.locator('[data-testid^="item-postmortem-"]').filter({ hasText: summary });
    await expect(card).toBeVisible({ timeout: 5_000 });
    await expect(card).toContainText('draft');

    await card.getByTestId('action-publish_postmortem').click();

    await expect(card).toContainText('published', { timeout: 5_000 });
    // Publishing locks it: no publish control remains once published.
    await expect(card.getByTestId('action-publish_postmortem')).toHaveCount(0);
  });

  test(`once published, a postmortem is visible to everyone and its content is locked from further edits`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();
    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);
      await inviteAndJoin(pageA, pageB);

      const title = uniqueName('incident');
      await pageA.getByTestId('field-title').fill(title);
      await pageA.getByTestId('field-description').fill('500s on checkout API');
      await pageA.getByTestId('field-severity').selectOption('Critical');
      await pageA.getByTestId('field-affected_area').fill('Payments');
      await pageA.getByTestId('action-create_incident').click();
      await pageA.locator('[data-testid^="item-incident-"]').filter({ hasText: title }).click();
      const incidentId = pageA.url().split('/incidents/')[1];

      await pageA.getByRole('link', { name: 'Postmortems' }).click();
      const summary = uniqueName('postmortem');
      await pageA.getByTestId('field-incident_id').fill(incidentId);
      await pageA.getByTestId('field-summary').fill(summary);
      await pageA.getByTestId('field-root_cause').fill('Bad deploy');
      await pageA.getByTestId('field-resolution_steps').fill('Rolled back');
      await pageA.getByTestId('field-lessons_learned').fill('Add canary tests');
      await pageA.getByTestId('action-create_postmortem').click();

      const cardA = pageA.locator('[data-testid^="item-postmortem-"]').filter({ hasText: summary });
      await expect(cardA).toBeVisible({ timeout: 5_000 });
      await cardA.getByTestId('action-publish_postmortem').click();
      await expect(cardA).toContainText('published', { timeout: 5_000 });

      // Everyone (B) can browse it, published, once it syncs.
      await pageB.getByRole('link', { name: 'Postmortems' }).click();
      const cardB = pageB.locator('[data-testid^="item-postmortem-"]').filter({ hasText: summary });
      await expect(cardB).toBeVisible({ timeout: 5_000 });
      await expect(cardB).toContainText('published');
      // Locked: no publish/edit control is offered for a published postmortem.
      await expect(cardB.getByTestId('action-publish_postmortem')).toHaveCount(0);
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
