// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect, type Page } from '@playwright/test';
import { loginViaHash, clearAuth } from './helpers';

async function ensureWorkspace(page: Page): Promise<void> {
  const noWs = await page.getByText('No workspaces yet').isVisible({ timeout: 4_000 }).catch(() => false);
  if (noWs) {
    await page.getByRole('button', { name: 'Create workspace' }).first().click();
    await page.getByRole('dialog').getByRole('button', { name: 'Create workspace' }).click();
    await expect(page.getByText('Incident Dashboard')).toBeVisible({ timeout: 15_000 });
  }
}

/** Report → open detail → acknowledge → resolve. Leaves the resolved detail in view. */
async function createResolvedIncident(page: Page, title: string): Promise<void> {
  await page.getByRole('button', { name: '\u26a1 Report Incident' }).click();
  await page.getByRole('button', { name: 'P2' }).click();
  await page.getByPlaceholder('Brief incident title\u2026').fill(title);
  await page.getByPlaceholder('What is happening? Impact? Timeline?').fill('Postmortem test incident');
  await page.getByRole('button', { name: 'Report Incident', exact: true }).click();
  await expect(page.getByText(title)).toBeVisible({ timeout: 10_000 });
  await page.getByText(title).first().click();
  await page.getByRole('button', { name: 'Acknowledge' }).click();
  await expect(page.getByText('acknowledged').first()).toBeVisible({ timeout: 5_000 });
  await page.getByRole('button', { name: 'Resolve' }).click();
  await expect(page.getByText('Resolve Incident')).toBeVisible({ timeout: 5_000 });
  await page.getByPlaceholder('What caused this incident?').fill('Missing rate limit on auth endpoint');
  await page.getByRole('button', { name: 'Mark Resolved' }).click();
  await expect(page.getByText(/\u2705 Resolved/)).toBeVisible({ timeout: 10_000 });
}

test.describe(`team member: write and collaboratively edit a postmortem after an incident is resolved`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await ensureWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`any team member can create a postmortem linked to a resolved incident with summary, root cause, and action items fields`, async ({ page }) => {
    const title = 'E2E-PM-Create';

    await createResolvedIncident(page, title);

    // Navigate to postmortem editor via resolved box link
    await page.getByRole('button', { name: 'Open Postmortem \u2192' }).click();

    // All three fields are visible
    await expect(page.getByText('Summary')).toBeVisible({ timeout: 5_000 });
    await expect(page.getByText('Root Cause')).toBeVisible({ timeout: 5_000 });
    await expect(page.getByText('Action Items')).toBeVisible({ timeout: 5_000 });

    // Fill in all three fields
    await page.getByPlaceholder('What happened? What was the impact?').fill('Pool exhaustion caused 12 min outage');
    await page.getByPlaceholder('Why did this happen? The underlying cause.').fill('Auth middleware leaked connections on timeout');
    await page.getByPlaceholder('1. Add alerting for X').fill('1. Add connection timeout\n2. Add pool usage alert');

    // Save the postmortem
    await page.getByRole('button', { name: 'Save' }).click();

    // Confirm save by observing the button transition to "Saved"
    await expect(page.getByRole('button', { name: /Saved|Save/ })).toBeVisible({ timeout: 10_000 });
  });

  test(`any team member can edit the postmortem and all others see the latest version within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    const pageA = await ctxA.newPage();
    const pageB = await ctxB.newPage();

    try {
      await loginViaHash(pageA, 0);
      await loginViaHash(pageB, 1);
      await ensureWorkspace(pageA);

      const noWsB = await pageB.getByText('No workspaces yet').isVisible({ timeout: 4_000 }).catch(() => false);
      if (noWsB) {
        await pageA.getByRole('button', { name: '+ Invite' }).click();
        await pageA.getByRole('button', { name: 'Generate invite code' }).click();
        await expect(pageA.locator('label', { hasText: 'Invite code' })).toBeVisible({ timeout: 10_000 });
        const code = await pageA.locator('textarea').last().inputValue();
        await pageA.keyboard.press('Escape');
        await pageB.getByRole('button', { name: 'Join with invitation' }).click();
        await pageB.getByPlaceholder('Paste your invite code\u2026').fill(code);
        await pageB.getByRole('button', { name: 'Join workspace' }).click();
        await expect(pageB.getByText('Incident Dashboard')).toBeVisible({ timeout: 15_000 });
      }

      const title = 'E2E-PM-Collab';
      const updatedSummary = 'Updated: pool exhaustion caused 12 min outage for 30% of users';

      // Node 0: create a resolved incident and an initial postmortem
      await createResolvedIncident(pageA, title);
      await pageA.getByRole('button', { name: 'Open Postmortem \u2192' }).click();
      await pageA.getByPlaceholder('What happened? What was the impact?').fill('Initial summary');
      await pageA.getByPlaceholder('Why did this happen? The underlying cause.').fill('Auth middleware leak');
      await pageA.getByPlaceholder('1. Add alerting for X').fill('1. Add timeout');
      await pageA.getByRole('button', { name: 'Save' }).click();
      await expect(pageA.getByRole('button', { name: /\u2713 Saved/ })).toBeVisible({ timeout: 10_000 });

      // Node 0 edits the summary
      await pageA.getByPlaceholder('What happened? What was the impact?').fill(updatedSummary);
      await pageA.getByRole('button', { name: 'Save' }).click();
      await expect(pageA.getByRole('button', { name: /\u2713 Saved/ })).toBeVisible({ timeout: 10_000 });

      // Node 1 navigates to the same incident postmortem and sees the updated text
      await expect(pageB.getByText(title)).toBeVisible({ timeout: 5_000 });
      await pageB.getByText(title).first().click();
      await expect(pageB.getByText(/\u2705 Resolved/)).toBeVisible({ timeout: 5_000 });
      await pageB.getByRole('button', { name: 'Open Postmortem \u2192' }).click();

      await expect(pageB.getByDisplayValue(updatedSummary)).toBeVisible({ timeout: 5_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
