/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Event_TaskAdded {
  id: string;
}

export interface Event_TaskDeleted {
  id: string;
}

export interface Event_TaskEdited {
  id: string;
}

export interface Event_TaskToggled {
  id: string;
}

export interface Task {
  id: string;
  author: string;
  description: string;
  done: boolean;
  created_at: number;
}

export interface TodoListState {
  tasks: Record<string, Task>;
}





export type AbiEvent =
  | { name: "TaskAdded"; payload: Event_TaskAdded }
  | { name: "TaskEdited"; payload: Event_TaskEdited }
  | { name: "TaskToggled"; payload: Event_TaskToggled }
  | { name: "TaskDeleted"; payload: Event_TaskDeleted }
;


export class TodolistClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * add_task
   */
  public async addTask(params: { description: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'add_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * edit_task
   */
  public async editTask(params: { task_id: string; new_description: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'edit_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * toggle_task_done
   */
  public async toggleTaskDone(params: { task_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'toggle_task_done', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_task
   */
  public async deleteTask(params: { task_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_tasks
   */
  public async listTasks(): Promise<Task[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_tasks', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Task[];
  }

}