/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Event_TaskAssigned {
  id: string;
}

export interface Event_TaskCreated {
  id: string;
}

export interface Event_TaskDeleted {
  id: string;
}

export interface Event_TaskToggled {
  id: string;
  completed: boolean;
}

export interface Task {
  id: string;
  title: string;
  completed: boolean;
  assigned_to: string | null;
  created_by: string;
  created_at: number;
  updated_at_ms: number;
}

export interface TodoState {
  tasks: Record<string, Task>;
}





export type AbiEvent =
  | { name: "TaskCreated"; payload: Event_TaskCreated }
  | { name: "TaskToggled"; payload: Event_TaskToggled }
  | { name: "TaskAssigned"; payload: Event_TaskAssigned }
  | { name: "TaskDeleted"; payload: Event_TaskDeleted }
;


export class TodolistClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * create_task
   */
  public async createTask(params: { title: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * toggle_task
   */
  public async toggleTask(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'toggle_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * assign_task
   */
  public async assignTask(params: { id: string; assignee: string | null }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'assign_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_task
   */
  public async deleteTask(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_tasks
   */
  public async listTasks(): Promise<Task[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_tasks', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Task[];
  }

}