/** @generated by @calimero/abi-codegen — fixed per codegen patch rules. */

import { MeroJs } from '@calimero-network/mero-react';

// ── Generated types ────────────────────────────────────────────────────────

export interface Task {
  id: string;
  title: string;
  author: string;
  assigned_to: string | null;
  completed: boolean;
  created_at: number;
}

export type AbiEvent =
  | { name: 'TaskCreated';    payload: { id: string } }
  | { name: 'TaskCompleted';  payload: { id: string } }
  | { name: 'TaskIncompleted'; payload: { id: string } }
  | { name: 'TaskEdited';     payload: { id: string } }
  | { name: 'TaskDeleted';    payload: { id: string } }
  | { name: 'TaskAssigned';   payload: { id: string } }
;

// ── Client ─────────────────────────────────────────────────────────────────

export class TodolistClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /** create_task — creates a new task owned by the caller; returns the generated task id. */
  public async createTask(params: { title: string }): Promise<string> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'create_task',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
    return response as string;
  }

  /** list_tasks — returns all tasks (open and completed). */
  public async listTasks(): Promise<Task[]> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'list_tasks',
      argsJson: {},
      executorPublicKey: this._executorPublicKey,
    });
    return response as Task[];
  }

  /** mark_complete — marks a task as completed. */
  public async markComplete(params: { task_id: string }): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'mark_complete',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
  }

  /** mark_incomplete — reverts a task to open. */
  public async markIncomplete(params: { task_id: string }): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'mark_incomplete',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
  }

  /** edit_task — updates the task title (author only). */
  public async editTask(params: { task_id: string; new_title: string }): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'edit_task',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
  }

  /** delete_task — removes a task (author only). */
  public async deleteTask(params: { task_id: string }): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'delete_task',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
  }

  /** assign_task — assigns a task to a team member. */
  public async assignTask(params: { task_id: string; assignee: string }): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'assign_task',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
  }
}
