/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Character {
  id: string;
  author: string;
  name: string;
  class_: string;
  strength: number;
  dexterity: number;
  constitution: number;
  intelligence: number;
  wisdom: number;
  charisma: number;
  hp_current: number;
  hp_max: number;
  created_at: number;
  updated_at: number;
}

export interface Event_CharacterCreated {
  id: string;
  name: string;
}

export interface Event_DifficultySet {
  dc: number;
}

export interface Event_GameCreated {
  id: string;
  name: string;
}

export interface Event_GameStateChanged {
  state: string;
}

export interface Event_HPAdjusted {
  character_id: string;
  hp: number;
}

export interface Event_RollMade {
  id: string;
  total: number;
}

export interface Event_TurnAdvanced {
  player: string;
}

export interface GameSession {
  id: string;
  dm_id: string;
  name: string;
  game_state: string;
  current_dc: number | null;
  current_turn_player: string | null;
  turn_order: string[];
  turn_index: number;
  created_at: number;
}

export interface TableEvent {
  id: string;
  author: string;
  event_type: string;
  timestamp: number;
  content: string;
  ability: string | null;
  d20_roll: number | null;
  modifier: number | null;
  total: number | null;
}

export interface TableState {
  session: GameSession;
  characters: Record<string, Character>;
  log: Record<string, TableEvent>;
}









export type AbiEvent =
  | { name: "GameCreated"; payload: Event_GameCreated }
  | { name: "CharacterCreated"; payload: Event_CharacterCreated }
  | { name: "MessagePosted" }
  | { name: "RollMade"; payload: Event_RollMade }
  | { name: "HPAdjusted"; payload: Event_HPAdjusted }
  | { name: "GameStateChanged"; payload: Event_GameStateChanged }
  | { name: "TurnAdvanced"; payload: Event_TurnAdvanced }
  | { name: "DifficultySet"; payload: Event_DifficultySet }
;


export class TableClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * create_character
   */
  public async createCharacter(params: { name: string; class_: string; str: number; dex: number; con: number; int_: number; wis: number; cha: number }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_character', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * get_my_character
   */
  public async getMyCharacter(): Promise<Character> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_my_character', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Character;
  }

  /**
   * get_all_characters
   */
  public async getAllCharacters(): Promise<Character[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_all_characters', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Character[];
  }

  /**
   * create_game
   */
  public async createGame(params: { name: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_game', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * invite_player
   */
  public async invitePlayer(params: { player_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'invite_player', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_game_info
   */
  public async getGameInfo(): Promise<GameSession> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_game_info', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as GameSession;
  }

  /**
   * set_game_state
   */
  public async setGameState(params: { state: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_game_state', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * set_difficulty
   */
  public async setDifficulty(params: { dc: number }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_difficulty', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * set_turn_order
   */
  public async setTurnOrder(params: { players: string[] }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_turn_order', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * advance_turn
   */
  public async advanceTurn(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'advance_turn', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * post_message
   */
  public async postMessage(params: { text: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'post_message', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * roll_for_player
   */
  public async rollForPlayer(params: { player_id: string; ability: string; reason: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'roll_for_player', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * roll_npc
   */
  public async rollNpc(params: { npc_name: string; modifier: number; reason: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'roll_npc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * adjust_hp
   */
  public async adjustHp(params: { character_id: string; delta: number }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'adjust_hp', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_game_log
   */
  public async getGameLog(): Promise<TableEvent[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_game_log', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as TableEvent[];
  }

}