/** @generated by @calimero/abi-codegen (manually authored for todos ABI) */

import { MeroJs } from '@calimero-network/mero-react';

// ── Entity types ─────────────────────────────────────────────────────────────

export interface Task {
  id: string;
  title: string;
  description: string;
  author: string;
  assigned_to: string | null;
  is_complete: boolean;
  created_at: number;
}

// ── Event types ───────────────────────────────────────────────────────────────

export type AbiEvent =
  | { name: 'TaskCreated' }
  | { name: 'TaskAssigned' }
  | { name: 'TaskCompleted' }
  | { name: 'TaskEdited' }
  | { name: 'TaskDeleted' };

// ── Client ────────────────────────────────────────────────────────────────────

export class TodosClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /** create_task — mutate */
  public async createTask(params: { title: string; description: string }): Promise<string> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'create_task',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
    return response as string;
  }

  /** assign_task — mutate */
  public async assignTask(params: { task_id: string; assignee: string }): Promise<void> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'assign_task',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
    return response as void;
  }

  /** complete_task — mutate */
  public async completeTask(params: { task_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'complete_task',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
    return response as void;
  }

  /** edit_task — mutate (author-only, enforced server-side) */
  public async editTask(params: { task_id: string; title: string; description: string }): Promise<void> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'edit_task',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
    return response as void;
  }

  /** delete_task — mutate (author-only, enforced server-side) */
  public async deleteTask(params: { task_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'delete_task',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
    return response as void;
  }

  /** list_tasks — view */
  public async listTasks(): Promise<Task[]> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'list_tasks',
      argsJson: {},
      executorPublicKey: this._executorPublicKey,
    });
    return response as Task[];
  }
}
