/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Event_TaskAssigned {
  id: string;
  assignee: string;
}

export interface Event_TaskCompleted {
  id: string;
}

export interface Event_TaskCreated {
  id: string;
  title: string;
}

export interface Event_TaskDeleted {
  id: string;
}

export interface Event_TaskEdited {
  id: string;
}

export interface Event_TaskReopened {
  id: string;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  creator: string;
  assigned_to: string | null;
  completed: boolean;
  created_at: number;
}

export interface TodoState {
  tasks: Record<string, Task>;
}







export type AbiEvent =
  | { name: "TaskCreated"; payload: Event_TaskCreated }
  | { name: "TaskCompleted"; payload: Event_TaskCompleted }
  | { name: "TaskReopened"; payload: Event_TaskReopened }
  | { name: "TaskEdited"; payload: Event_TaskEdited }
  | { name: "TaskDeleted"; payload: Event_TaskDeleted }
  | { name: "TaskAssigned"; payload: Event_TaskAssigned }
;


export class TodoClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * create_task
   */
  public async createTask(params: { title: string; description: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * complete_task
   */
  public async completeTask(params: { task_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'complete_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * reopen_task
   */
  public async reopenTask(params: { task_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'reopen_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * edit_task
   */
  public async editTask(params: { task_id: string; title: string; description: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'edit_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_task
   */
  public async deleteTask(params: { task_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * assign_task
   */
  public async assignTask(params: { task_id: string; assignee: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'assign_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_tasks
   */
  public async listTasks(): Promise<Task[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_tasks', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Task[];
  }

}