/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Cell {
  id: string;
  sheet_id: string;
  row: number;
  col: number;
  raw_value: string;
  computed_value: string;
  updated_at: number;
}

export interface CellData {
  id: string;
  sheet_id: string;
  row: number;
  col: number;
  raw_value: string;
  computed_value: string;
  updated_at: number;
}

export interface Cursor {
  id: string;
  author: string;
  sheet_id: string;
  row: number;
  col: number;
  color: string;
  updated_at: number;
}

export interface CursorData {
  sheet_id: string;
  row: number;
  col: number;
  color: string;
  updated_at: number;
}

export interface Event_CellCleared {
  sheet_id: string;
  row: number;
  col: number;
}

export interface Event_CellUpdated {
  id: string;
  sheet_id: string;
}

export interface Event_CursorMoved {
  author: string;
  sheet_id: string;
}

export interface Event_CursorRemoved {
  author: string;
}

export interface Event_ProjectInitialized {
  id: string;
  name: string;
}

export interface Event_SheetCreated {
  id: string;
  name: string;
}

export interface Event_SheetDeleted {
  id: string;
}

export interface Event_SheetRenamed {
  id: string;
  name: string;
}

export interface FunctionDef {
  name: string;
  syntax: string;
  description: string;
  example: string;
}

export interface Sheet {
  id: string;
  name: string;
  position: number;
  created_at: number;
}

export interface SheetData {
  id: string;
  name: string;
  position: number;
  created_at: number;
  updated_at: number;
}

export interface Spreadsheet {
  project_id: string;
  project_name: string;
  project_created_at: number;
  sheets: Record<string, SheetData>;
  cells: Record<string, CellData>;
  cursors: Record<string, CursorData>;
}









export type AbiEvent =
  | { name: "ProjectInitialized"; payload: Event_ProjectInitialized }
  | { name: "SheetCreated"; payload: Event_SheetCreated }
  | { name: "SheetRenamed"; payload: Event_SheetRenamed }
  | { name: "SheetDeleted"; payload: Event_SheetDeleted }
  | { name: "CellUpdated"; payload: Event_CellUpdated }
  | { name: "CellCleared"; payload: Event_CellCleared }
  | { name: "CursorMoved"; payload: Event_CursorMoved }
  | { name: "CursorRemoved"; payload: Event_CursorRemoved }
;


export class SpreadsheetClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * init_project
   */
  public async initProject(params: { name: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init_project', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * create_sheet
   */
  public async createSheet(params: { name: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_sheet', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * rename_sheet
   */
  public async renameSheet(params: { sheet_id: string; new_name: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'rename_sheet', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_sheet
   */
  public async deleteSheet(params: { sheet_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_sheet', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_sheets
   */
  public async listSheets(): Promise<Sheet[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_sheets', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Sheet[];
  }

  /**
   * set_cell
   */
  public async setCell(params: { sheet_id: string; row: number; col: number; raw_value: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_cell', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * set_cell_formula
   */
  public async setCellFormula(params: { sheet_id: string; row: number; col: number; formula: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_cell_formula', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * clear_cell
   */
  public async clearCell(params: { sheet_id: string; row: number; col: number }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'clear_cell', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_cells
   */
  public async getCells(params: { sheet_id: string }): Promise<Cell[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_cells', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as Cell[];
  }

  /**
   * update_cursor
   */
  public async updateCursor(params: { sheet_id: string; row: number; col: number }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'update_cursor', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * remove_cursor
   */
  public async removeCursor(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'remove_cursor', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_cursors
   */
  public async getCursors(): Promise<Cursor[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_cursors', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Cursor[];
  }

  /**
   * get_functions
   */
  public async getFunctions(): Promise<FunctionDef[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_functions', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as FunctionDef[];
  }

  /**
   * search_functions
   */
  public async searchFunctions(params: { prefix: string }): Promise<FunctionDef[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'search_functions', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as FunctionDef[];
  }

  /**
   * export_all
   */
  public async exportAll(): Promise<Sheet[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'export_all', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Sheet[];
  }

}