/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Event_LeadAdded {
  id: string;
}

export interface Event_LeadClosed {
  id: string;
  outcome: string;
}

export interface Event_LeadMoved {
  id: string;
  stage: string;
}

export interface Lead {
  id: string;
  name: string;
  company: string;
  value: number;
  stage: string;
  status: string;
  created_by: string;
  created_at: number;
  last_modified_ms: number;
}

export interface PipelineConfig {
  id: string;
  stages: string[];
  updated_at: number;
}

export interface PipelineState {
  config: Record<string, PipelineConfig>;
  leads: Record<string, Lead>;
}





export type AbiEvent =
  | { name: "StagesUpdated" }
  | { name: "LeadAdded"; payload: Event_LeadAdded }
  | { name: "LeadMoved"; payload: Event_LeadMoved }
  | { name: "LeadClosed"; payload: Event_LeadClosed }
;


export class PipelineClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * set_stages
   */
  public async setStages(params: { stages: string[] }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_stages', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_stages
   */
  public async getStages(): Promise<string[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_stages', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as string[];
  }

  /**
   * add_lead
   */
  public async addLead(params: { name: string; company: string; value: number }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'add_lead', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * move_lead
   */
  public async moveLead(params: { lead_id: string; new_stage: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'move_lead', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * close_lead
   */
  public async closeLead(params: { lead_id: string; outcome: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'close_lead', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_leads
   */
  public async listLeads(): Promise<Lead[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_leads', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Lead[];
  }

  /**
   * list_closed_leads
   */
  public async listClosedLeads(): Promise<Lead[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_closed_leads', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Lead[];
  }

}