/** @generated by @calimero/abi-codegen — pipeline service. Fixed: Rust types → TS. */

import { MeroJs } from '@calimero-network/mero-react';

// ── Generated types ───────────────────────────────────────────────────────────

export interface Lead {
  id: string;
  name: string;
  company: string;
  /** u64 in Rust → number in TS (safe for dollar amounts ≤ 2^53). */
  value: number;
  stage: string;
  /** 'active' | 'closed' */
  status: string;
  created_by: string;
  /** Unix epoch ms. */
  created_at: number;
}

export type AbiEvent =
  | { name: 'StagesUpdated' }
  | { name: 'LeadAdded'; payload: { id: string } }
  | { name: 'LeadMoved'; payload: { id: string; new_stage: string } }
  | { name: 'LeadClosed'; payload: { id: string; outcome: string } }
;

// ── Client ────────────────────────────────────────────────────────────────────

export class PipelineClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /** set_stages — replace the pipeline stage list (mutate). */
  public async setStages(params: { stages: string[] }): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'set_stages',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
  }

  /** get_stages — return the current stage list (view). */
  public async getStages(): Promise<string[]> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'get_stages',
      argsJson: {},
      executorPublicKey: this._executorPublicKey,
    });
    return response as string[];
  }

  /** add_lead — create a new lead in the first stage (mutate). Returns the new lead id. */
  public async addLead(params: { name: string; company: string; value: number }): Promise<string> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'add_lead',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
    return response as string;
  }

  /** move_lead — move a lead to a different stage (mutate). */
  public async moveLead(params: { lead_id: string; new_stage: string }): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'move_lead',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
  }

  /** close_lead — mark a lead as Won or Lost and remove it from the active pipeline (mutate). */
  public async closeLead(params: { lead_id: string; outcome: string }): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'close_lead',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
  }

  /** list_leads — return all active leads (view). */
  public async listLeads(): Promise<Lead[]> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'list_leads',
      argsJson: {},
      executorPublicKey: this._executorPublicKey,
    });
    return response as Lead[];
  }

  /** list_closed_leads — return all closed (Won/Lost) leads (view). */
  public async listClosedLeads(): Promise<Lead[]> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'list_closed_leads',
      argsJson: {},
      executorPublicKey: this._executorPublicKey,
    });
    return response as Lead[];
  }
}
