/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Event_KudosDeleted {
  id: string;
}

export interface Event_KudosPosted {
  id: string;
}

export interface Kudos {
  id: string;
  author: string;
  recipient: string;
  message: string;
  created_at: number;
}

export interface KudosBoardState {
  kudos: Record<string, Kudos>;
}



export type AbiEvent =
  | { name: "KudosPosted"; payload: Event_KudosPosted }
  | { name: "KudosDeleted"; payload: Event_KudosDeleted }
;


export class KudosBoardClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * post_kudos
   */
  public async postKudos(params: { recipient: string; message: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'post_kudos', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * get_feed
   */
  public async getFeed(): Promise<Kudos[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_feed', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Kudos[];
  }

  /**
   * delete_kudos
   */
  public async deleteKudos(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_kudos', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

}