/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface CommunitySummary {
  id: string;
  name: string;
  topic: string;
  context_id: string | null;
  created_by: string;
  member_count: number;
  created_at: number;
}

export interface Event_CommunityDeleted {
  id: string;
}

export interface Event_CommunityRegistered {
  id: string;
  name: string;
}

export interface Event_CommunityStatsUpdated {
  id: string;
}

export interface HubState {
  communities: Record<string, CommunitySummary>;
}




export type AbiEvent =
  | { name: "CommunityRegistered"; payload: Event_CommunityRegistered }
  | { name: "CommunityStatsUpdated"; payload: Event_CommunityStatsUpdated }
  | { name: "CommunityDeleted"; payload: Event_CommunityDeleted }
;


export class HubClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * register_community
   */
  public async registerCommunity(params: { community_id: string; name: string; topic: string; context_id: string }): Promise<CommunitySummary> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'register_community', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as CommunitySummary;
  }

  /**
   * get_communities
   */
  public async getCommunities(): Promise<CommunitySummary[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_communities', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as CommunitySummary[];
  }

  /**
   * update_community_stats
   */
  public async updateCommunityStats(params: { community_id: string; member_count: number }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'update_community_stats', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_community
   */
  public async deleteCommunity(params: { community_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_community', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

}