//! Convergence coverage for the issue-tracker service.
//!
//! `Task` and `Category` derive `Mergeable` (`#[derive(Mergeable)]`), which
//! also generates the `RekeyTarget` needed because they nest `LwwRegister`
//! fields — without deterministic re-keying, a nested register would be
//! last-writer-wins'd as an opaque blob instead of converging field-by-field.
//! We register the generated re-key thunks (`__calimero_register_rekey()`)
//! then assert every replica lands on the same Merkle root after concurrent
//! writes to the SAME task field.
//!
//! Surface under test: the `categories`/`tasks` `UnorderedMap` fields only.
//! The sibling `comments: AuthoredMap` merges on the *signed* delta path
//! (`Interface::apply_action`) — the bare `converge_app` harness has no
//! signing identity and cannot reconcile `AuthoredMap` entries (see
//! `core/crates/storage/src/testing.rs` Limitations). So we seed a category
//! and a task at **genesis** (single identity, snapshotted identically into
//! every replica) and drive only `set_priority`, which touches `tasks`
//! exclusively.
//!
//! `#[serial]`: `converge_app` clears/repopulates the process-global merge
//! registry per run. Own integration binary so it is isolated from the
//! in-`lib.rs` `TestHost` unit tests.

use calimero_storage::testing::converge_app;
use serial_test::serial;
use team_issue_tracker_issue_tracker::IssueTracker;

// One category and one task are seeded at genesis (under the genesis
// identity, before any concurrent op), so every replica starts from the
// identical seeded state. Each replica then concurrently sets the task's
// priority to the same value. The derived `Mergeable` + generated
// `RekeyTarget` on `Task` must converge all replicas to one Merkle root, and
// the priority must survive as the merged (not stale/opaque-blob) value.
#[test]
#[serial]
fn task_priority_converges() {
    // Register the nested-CRDT-value re-key thunks generated by
    // `#[derive(Mergeable)]` on `Category`/`Task`. Without this the structs
    // would be LWW'd as opaque blobs and replicas could diverge.
    IssueTracker::__calimero_register_rekey();

    converge_app(|| {
        // Genesis seed: runs once under the single genesis identity, so the
        // `comments` AuthoredMap is never touched, then snapshotted
        // byte-identical into every replica.
        let mut s = IssueTracker::init();
        let cat = s.create_category("Backend".into()).unwrap();
        let _ = s.create_task(
            "Fix login bug".into(),
            "Users can't log in on Safari".into(),
            cat,
            "alice".into(),
        );
        s
    })
    .replicas(3)
    // Each replica concurrently rewrites the single seeded task's priority.
    // `set_priority` touches `tasks` only (no `comments` write), so this is
    // the pure nested-register convergence case.
    .ops(|s| {
        if let Some(view) = s.list_tasks(true).ok().and_then(|v| v.into_iter().next()) {
            let _ = s.set_priority(view.id, "urgent".into());
        }
    })
    .invariant(
        "the single seeded task survives and holds the merged priority",
        |s| {
            let tasks = s.list_tasks(true).unwrap_or_default();
            tasks.len() == 1 && tasks[0].priority == "urgent"
        },
    )
    .assert_all_replicas_equal();
}
