/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Event_MemoryAdded {
  id: string;
}

export interface Event_MemoryDeleted {
  id: string;
}

export interface Event_MemoryUpdated {
  id: string;
}

export interface MemoryItem {
  id: string;
  text: string;
  tags: string[];
  author: string;
  created_at: number;
  updated_at: number;
}

export interface SoulState {
  memories: Record<string, MemoryItem>;
}




export type AbiEvent =
  | { name: "MemoryAdded"; payload: Event_MemoryAdded }
  | { name: "MemoryUpdated"; payload: Event_MemoryUpdated }
  | { name: "MemoryDeleted"; payload: Event_MemoryDeleted }
;


export class SoulClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * add_memory
   */
  public async addMemory(params: { text: string; tags: string[] }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'add_memory', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * update_memory
   */
  public async updateMemory(params: { id: string; text: string; tags: string[] }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'update_memory', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_memory
   */
  public async deleteMemory(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_memory', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_memories
   */
  public async listMemories(): Promise<MemoryItem[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_memories', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as MemoryItem[];
  }

  /**
   * query_by_tags
   */
  public async queryByTags(params: { tags: string[] }): Promise<MemoryItem[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'query_by_tags', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as MemoryItem[];
  }

}