/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Category {
  id: string;
  name: string;
  created_at: number;
}

export interface CategoryView {
  id: string;
  name: string;
  created_at: number;
}

export interface Comment {
  id: string;
  task_id: string;
  author: string;
  body: string;
  pr_link: string;
  created_at: number;
  updated_at: number;
}

export interface CommentView {
  id: string;
  task_id: string;
  author: string;
  body: string;
  pr_link: string | null;
  created_at: number;
  updated_at: number;
}

export interface Event_CategoryCreated {
  id: string;
  name: string;
}

export interface Event_CommentAdded {
  id: string;
  task_id: string;
}

export interface Event_CommentDeleted {
  id: string;
}

export interface Event_CommentEdited {
  id: string;
}

export interface Event_TaskArchived {
  id: string;
}

export interface Event_TaskAssigned {
  id: string;
  assignee: string;
}

export interface Event_TaskCompleted {
  id: string;
}

export interface Event_TaskCreated {
  id: string;
  title: string;
  assignee: string;
}

export interface Event_TaskMoved {
  id: string;
  category_id: string;
}

export interface Event_TaskPriorityChanged {
  id: string;
  priority: string;
}

export interface IssueTracker {
  categories: Record<string, Category>;
  tasks: Record<string, Task>;
  comments: Record<string, Comment>;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  assignee: string;
  priority: string;
  status: string;
  archived: boolean;
  category_id: string;
  author: string;
  created_at: number;
}

export interface TaskView {
  id: string;
  title: string;
  description: string;
  assignee: string;
  priority: string;
  status: string;
  archived: boolean;
  category_id: string;
  author: string;
  created_at: number;
}











export type AbiEvent =
  | { name: "CategoryCreated"; payload: Event_CategoryCreated }
  | { name: "TaskCreated"; payload: Event_TaskCreated }
  | { name: "TaskAssigned"; payload: Event_TaskAssigned }
  | { name: "TaskPriorityChanged"; payload: Event_TaskPriorityChanged }
  | { name: "TaskMoved"; payload: Event_TaskMoved }
  | { name: "TaskCompleted"; payload: Event_TaskCompleted }
  | { name: "TaskArchived"; payload: Event_TaskArchived }
  | { name: "CommentAdded"; payload: Event_CommentAdded }
  | { name: "CommentEdited"; payload: Event_CommentEdited }
  | { name: "CommentDeleted"; payload: Event_CommentDeleted }
;


export class IssueTrackerClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * create_category
   */
  public async createCategory(params: { name: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_category', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * list_categories
   */
  public async listCategories(): Promise<CategoryView[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_categories', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as CategoryView[];
  }

  /**
   * create_task
   */
  public async createTask(params: { title: string; description: string; category_id: string; assignee: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * assign_task
   */
  public async assignTask(params: { task_id: string; assignee: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'assign_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * set_priority
   */
  public async setPriority(params: { task_id: string; priority: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_priority', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * move_task
   */
  public async moveTask(params: { task_id: string; category_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'move_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * complete_task
   */
  public async completeTask(params: { task_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'complete_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * archive_task
   */
  public async archiveTask(params: { task_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'archive_task', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_tasks
   */
  public async listTasks(params: { include_archived: boolean }): Promise<TaskView[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_tasks', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as TaskView[];
  }

  /**
   * add_comment
   */
  public async addComment(params: { task_id: string; body: string; pr_link: string | null }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'add_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * edit_comment
   */
  public async editComment(params: { comment_id: string; body: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'edit_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_comment
   */
  public async deleteComment(params: { comment_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_comments
   */
  public async listComments(params: { task_id: string }): Promise<CommentView[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_comments', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as CommentView[];
  }

}