/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Duel {
  id: string;
  initiator: string;
  status: string;
  duration_seconds: number;
  started_at: number;
  ended_at: number | null;
}

export interface DuelRecord {
  initiator: string;
  status: string;
  duration_seconds: number;
  started_at: number;
  ended_at: number;
}

export interface DuelResult {
  id: string;
  duel_id: string;
  author: string;
  score: number;
  length: number;
  created_at: number;
}

export interface DuelResultData {
  duel_id: string;
  score: number;
  length: number;
  created_at: number;
}

export interface Event_DuelFinished {
  id: string;
}

export interface Event_DuelResultSubmitted {
  id: string;
  duel_id: string;
  author: string;
}

export interface Event_DuelStarted {
  id: string;
  initiator: string;
}

export interface Event_MemberStatusUpdated {
  player: string;
}

export interface PlayerStatus {
  player: string;
  status: string;
  live_score: number;
  live_length: number;
  best_score: number;
  updated_at: number;
}

export interface PlayerStatusData {
  status: string;
  live_score: number;
  live_length: number;
  best_score: number;
  updated_at: number;
}

export interface RoomState {
  members: Record<string, PlayerStatusData>;
  duels: Record<string, DuelRecord>;
  duel_results: Record<string, DuelResultData>;
}





export type AbiEvent =
  | { name: "MemberStatusUpdated"; payload: Event_MemberStatusUpdated }
  | { name: "DuelStarted"; payload: Event_DuelStarted }
  | { name: "DuelResultSubmitted"; payload: Event_DuelResultSubmitted }
  | { name: "DuelFinished"; payload: Event_DuelFinished }
;


export class RoomClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * update_status
   */
  public async updateStatus(params: { status: string; score: number; length: number }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'update_status', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_members
   */
  public async listMembers(): Promise<PlayerStatus[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_members', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as PlayerStatus[];
  }

  /**
   * get_leaderboard
   */
  public async getLeaderboard(): Promise<PlayerStatus[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_leaderboard', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as PlayerStatus[];
  }

  /**
   * start_duel
   */
  public async startDuel(params: { duration_seconds: number }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'start_duel', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * submit_duel_result
   */
  public async submitDuelResult(params: { duel_id: string; score: number; length: number }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'submit_duel_result', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * finish_duel
   */
  public async finishDuel(params: { duel_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'finish_duel', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_duels
   */
  public async getDuels(): Promise<Duel[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_duels', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Duel[];
  }

  /**
   * get_duel_results
   */
  public async getDuelResults(params: { duel_id: string }): Promise<DuelResult[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_duel_results', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as DuelResult[];
  }

}