/** @generated by @calimero/abi-codegen — fixed for team-expenses ABI. */

import { MeroJs } from '@calimero-network/mero-react';

// ── Domain types ────────────────────────────────────────────────────────────

export interface Expense {
  id: string;
  author: string;
  description: string;
  /** Stored as minor currency units (e.g. cents). u64 in Rust → number here. */
  amount: number;
  currency: string;
  category: string;
  /** "pending" | "approved" | "rejected" | "reimbursed" */
  status: string;
  reviewer_note: string;
  submitted_at: number;
}

export interface Category {
  id: string;
  name: string;
}

// ── Event payloads ──────────────────────────────────────────────────────────

export interface Event_ExpenseSubmitted { id: string }
export interface Event_ExpenseEdited    { id: string }
export interface Event_ExpenseApproved  { id: string }
export interface Event_ExpenseRejected  { id: string }
export interface Event_ExpenseReimbursed{ id: string }
export interface Event_CategoryAdded   { id: string }

export type AbiEvent =
  | { name: 'ExpenseSubmitted'; payload: Event_ExpenseSubmitted }
  | { name: 'ExpenseEdited';    payload: Event_ExpenseEdited }
  | { name: 'ExpenseApproved';  payload: Event_ExpenseApproved }
  | { name: 'ExpenseRejected';  payload: Event_ExpenseRejected }
  | { name: 'ExpenseReimbursed';payload: Event_ExpenseReimbursed }
  | { name: 'CategoryAdded';    payload: Event_CategoryAdded };

// ── Client ──────────────────────────────────────────────────────────────────

export class ExpensesClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  private async exec<T>(method: string, argsJson: Record<string, unknown> = {}): Promise<T> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method,
      argsJson,
      executorPublicKey: this._executorPublicKey,
    });
    return response as T;
  }

  // ── Mutations ─────────────────────────────────────────────────────────────

  /** Submit a new expense. Returns the generated expense id. */
  public async submitExpense(params: {
    description: string;
    amount: number;
    currency: string;
    category: string;
  }): Promise<string> {
    return this.exec<string>('submit_expense', params);
  }

  /** Edit a pending expense (only while status is "pending"). */
  public async editExpense(params: {
    expense_id: string;
    description: string;
    amount: number;
    currency: string;
    category: string;
  }): Promise<void> {
    return this.exec<void>('edit_expense', params);
  }

  /** Approve an expense with an optional note. Ops-only on the backend. */
  public async approveExpense(params: { expense_id: string; note: string }): Promise<void> {
    return this.exec<void>('approve_expense', params);
  }

  /** Reject an expense with a required note. Ops-only on the backend. */
  public async rejectExpense(params: { expense_id: string; note: string }): Promise<void> {
    return this.exec<void>('reject_expense', params);
  }

  /** Mark an approved expense as reimbursed. Ops-only on the backend. */
  public async markReimbursed(params: { expense_id: string }): Promise<void> {
    return this.exec<void>('mark_reimbursed', params);
  }

  /** Add a spend category. Returns the new category id. */
  public async addCategory(params: { name: string }): Promise<string> {
    return this.exec<string>('add_category', params);
  }

  // ── Queries ───────────────────────────────────────────────────────────────

  /** Expenses submitted by the calling identity (all statuses). */
  public async listMyExpenses(): Promise<Expense[]> {
    return this.exec<Expense[]>('list_my_expenses');
  }

  /** All expenses with status "pending" (for ops review). */
  public async listPendingExpenses(): Promise<Expense[]> {
    return this.exec<Expense[]>('list_pending_expenses');
  }

  /** Every expense across all authors and statuses. */
  public async listAllExpenses(): Promise<Expense[]> {
    return this.exec<Expense[]>('list_all_expenses');
  }

  /** All registered spend categories. */
  public async listCategories(): Promise<Category[]> {
    return this.exec<Category[]>('list_categories');
  }
}
