/** @generated by @calimero/abi-codegen — DO NOT EDIT (codegen-fixed). */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface CommunityMeta {
  id: string;
  name: string;
  topic: string;
  lobby_context_id: string | null;
}

export interface Moderator {
  id: string;
  member_id: string;
  appointed_at: number;
}

export interface Post {
  id: string;
  author: string;
  title: string;
  body: string;
  vote_score: number;
  comment_count: number;
  created_at: number;
}

export interface Comment {
  id: string;
  post_id: string;
  parent_comment_id: string | null;
  author: string;
  body: string;
  vote_score: number;
  created_at: number;
}

export interface Vote {
  id: string;
  target_id: string;
  target_type: string;
  author: string;
  value: number;
}

export interface Event_PostCreated {
  id: string;
  author: string;
  title: string;
}

export interface Event_PostEdited {
  id: string;
}

export interface Event_PostDeleted {
  id: string;
}

export interface Event_CommentCreated {
  id: string;
  post_id: string;
  author: string;
}

export interface Event_CommentEdited {
  id: string;
}

export interface Event_CommentDeleted {
  id: string;
}

export interface Event_VoteCast {
  target_id: string;
  target_type: string;
  value: number;
}

export interface Event_ModeratorAppointed {
  id: string;
  member_id: string;
}

export interface Event_ModeratorRevoked {
  id: string;
}

export interface Event_PostModerated {
  id: string;
}

export interface Event_CommentModerated {
  id: string;
}

export interface Event_CommunityRenamed {
  new_name: string;
  new_topic: string;
}

export type AbiEvent =
  | { name: 'PostCreated'; payload: Event_PostCreated }
  | { name: 'PostEdited'; payload: Event_PostEdited }
  | { name: 'PostDeleted'; payload: Event_PostDeleted }
  | { name: 'CommentCreated'; payload: Event_CommentCreated }
  | { name: 'CommentEdited'; payload: Event_CommentEdited }
  | { name: 'CommentDeleted'; payload: Event_CommentDeleted }
  | { name: 'VoteCast'; payload: Event_VoteCast }
  | { name: 'ModeratorAppointed'; payload: Event_ModeratorAppointed }
  | { name: 'ModeratorRevoked'; payload: Event_ModeratorRevoked }
  | { name: 'PostModerated'; payload: Event_PostModerated }
  | { name: 'CommentModerated'; payload: Event_CommentModerated }
  | { name: 'CommunityRenamed'; payload: Event_CommunityRenamed }
;


export class CommunityClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * create_post
   */
  public async createPost(params: { title: string; body: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_post', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * get_posts
   */
  public async getPosts(): Promise<Post[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_posts', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Post[];
  }

  /**
   * edit_post
   */
  public async editPost(params: { post_id: string; new_title: string; new_body: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'edit_post', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_post
   */
  public async deletePost(params: { post_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_post', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * create_comment
   */
  public async createComment(params: { post_id: string; body: string; parent_comment_id: string | null }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * get_comments
   */
  public async getComments(params: { post_id: string }): Promise<Comment[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_comments', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as Comment[];
  }

  /**
   * edit_comment
   */
  public async editComment(params: { comment_id: string; new_body: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'edit_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_comment
   */
  public async deleteComment(params: { comment_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * cast_vote
   */
  public async castVote(params: { target_id: string; target_type: string; value: number }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'cast_vote', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * appoint_moderator
   */
  public async appointModerator(params: { member_id: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'appoint_moderator', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * revoke_moderator
   */
  public async revokeModerator(params: { moderator_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'revoke_moderator', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_moderators
   */
  public async getModerators(): Promise<Moderator[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_moderators', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Moderator[];
  }

  /**
   * moderate_remove_post
   */
  public async moderateRemovePost(params: { post_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'moderate_remove_post', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * moderate_remove_comment
   */
  public async moderateRemoveComment(params: { comment_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'moderate_remove_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * rename_community
   */
  public async renameCommunity(params: { new_name: string; new_topic: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'rename_community', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }
}
