import React, { useEffect, useRef, useState } from 'react';
import styled, { keyframes } from 'styled-components';
import { ConnectButton, CalimeroLogo } from '@calimero-network/mero-react';
import { APP_DISPLAY_NAME, APP_DESCRIPTION } from '../../config';
import { C } from '../../theme';
import { Secondary, NARROW, WIDE } from '../../components/primitives';

/**
 * One-page marketing landing: the app's front door.
 *
 * White, professional Calimero aesthetic (neon green on paper + near-black),
 * mirroring Calimero Studio's landing. Scroll-reveal animations, an animated
 * live preview, a features grid and a FAQ about nodes / contexts / data.
 *
 * BUILD AGENT: customize the copy for the specific app: the headline, the
 * sub-headline, the three FEATURES, and the FAQ answers. Keep the structure,
 * the animations, the brand palette (C) and the auth wiring:
 *   - already authenticated (incl. desktop SSO skip) → go straight to the app
 *   - otherwise → animated landing + a ConnectButton CTA
 * Pull real product features from the spec; don't ship the placeholder copy.
 */

/* ConnectButton and its login popup style themselves from mero-react's own
   --mero-* tokens, a namespace disjoint from ours, so nothing on this page can
   reach them. The real constraint is narrower than it looks: never pass a
   `theme` prop to MeroProvider, which is what once broke the popup's contrast. */

/* Drawn marks, not emoji. An emoji set is the loudest "generated by a machine"
   tell a landing page has, it renders differently on every platform, and it
   cannot take the preset accent. These are stroked with currentColor so they do.

   BUILD AGENT: draw marks for YOUR domain the same way. Inline SVG or CSS only,
   never emoji and never an external asset. */
const IconPin = (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <path d="M12 21s7-6.5 7-11.5A7 7 0 0 0 5 9.5C5 14.5 12 21 12 21z" />
    <circle cx="12" cy="9.5" r="2.4" />
  </svg>
);
const IconVersions = (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <rect x="4" y="4" width="12" height="9" rx="1.5" />
    <path d="M8 17.5h12v-9" />
    <path d="M8 21.5h12v-9" />
  </svg>
);
const IconResolve = (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
    <circle cx="12" cy="12" r="8.5" />
    <path d="M8.3 12.3 10.8 14.8 15.9 9.4" />
  </svg>
);

const FEATURES = [
  { icon: IconPin, title: 'Pinned to the exact spot', body: 'Drop a comment right on the pixel it\u2019s about. No more "the button in the third row" guesswork.' },
  { icon: IconVersions, title: 'Every version, side by side', body: 'Upload a new mockup and the whole team sees it appear within seconds, ready for a fresh round of feedback.' },
  { icon: IconResolve, title: 'Resolved independently', body: 'Anyone can mark a pin resolved. It never touches the status of any other pin, so the open list only shows what\u2019s left.' },
];

const FAQS: [string, string][] = [
  ['What is a node?', 'A node (merod) is the runtime that stores your mockups and pins and runs the review logic. You run your own, locally or on your own infrastructure, so nothing lives on a third-party server.'],
  ['Where do my mockups and pins live?', 'On your own node, as CRDT collections that merge conflict-free across peers. There is no central database \u2014 take your node offline and your review board goes with it.'],
  ['What is a context?', 'A context is the shared review space your team joins by invitation. Everyone in it sees the same mockups and pins in real time, synced directly between nodes.'],
  ['How do teammates join a review?', 'Connect your node, then share an invitation link. Anyone you invite joins the context and can start pinning feedback instantly. No accounts, no sign-up.'],
  ['Can two people pin the same spot at once?', 'Yes. Pins are independent CRDT entries, so simultaneous feedback from different teammates merges cleanly \u2014 nobody\u2019s comment overwrites anyone else\u2019s.'],
  ['Do I need crypto or a wallet?', 'No. You connect with a node identity. There is no token, no wallet and no gas \u2014 just your node and the teammates you invite.'],
];

/* ── scroll-reveal hook + wrapper (variants: up / zoom / drop / left) ──────── */
function useReveal<T extends HTMLElement = HTMLDivElement>() {
  const ref = useRef<T>(null);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          el.classList.add('is-visible');
          obs.disconnect();
        }
      },
      { threshold: 0.14 },
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return ref;
}

type RVariant = 'up' | 'zoom' | 'drop' | 'left';
function R({
  v = 'up',
  d = 0,
  className,
  style,
  id,
  children,
}: {
  v?: RVariant;
  d?: number;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  children: React.ReactNode;
}) {
  const ref = useReveal<HTMLDivElement>();
  return (
    <RBox ref={ref} $v={v} $d={d} className={className} style={style} id={id}>
      {children}
    </RBox>
  );
}

const STEPS = [
  { k: '01', t: 'Connect your node', d: 'Point the app at the Calimero node you control. Your identity and keys stay on your machine.' },
  { k: '02', t: 'Upload a mockup', d: 'Drop in the latest version. Everyone in the review sees it appear within seconds.' },
  { k: '03', t: 'Pin the feedback', d: 'Click the exact spot on the image and leave a comment — tied to the pixel, not a screenshot with arrows.' },
  { k: '04', t: 'Resolve as you go', d: 'Anyone can mark a pin resolved, independently of the others, so the open list shrinks as work lands.' },
];

/* ── animated live preview: pins landing on a shared mockup, loops ─────────── */
type PreviewPin = { id: number; x: number; y: number; who: string };
const SCRIPT: PreviewPin[] = [
  { id: 1, x: 24, y: 64, who: 'M' },
  { id: 2, x: 70, y: 30, who: 'J' },
  { id: 3, x: 46, y: 80, who: 'you' },
];

function LivePreview() {
  const [shown, setShown] = useState<number[]>([]);
  const [resolved, setResolved] = useState<number[]>([]);
  const [pulse, setPulse] = useState(false);

  useEffect(() => {
    const timers: number[] = [];
    const at = (ms: number, fn: () => void) => timers.push(window.setTimeout(fn, ms));
    const run = () => {
      setShown([]);
      setResolved([]);
      SCRIPT.forEach((p, i) => {
        at(500 + i * 1100, () => {
          setShown((prev) => [...prev, p.id]);
          setPulse(true);
          at(350, () => setPulse(false));
        });
      });
      at(500 + SCRIPT.length * 1100 + 600, () => setResolved([SCRIPT[0].id]));
    };
    run();
    const loopMs = 500 + SCRIPT.length * 1100 + 600 + 2200;
    const loop = window.setInterval(run, loopMs);
    return () => { timers.forEach(window.clearTimeout); window.clearInterval(loop); };
  }, []);

  return (
    <Preview aria-hidden="true">
      <div className="bar">
        <s style={{ background: C.off }} />
        <s style={{ background: C.mutedSoft }} />
        <s style={{ background: C.green }} />
        <span><CalimeroLogo size={13} color={C.green} /> {APP_DISPLAY_NAME.toLowerCase()} · your node</span>
        <em className={pulse ? 'on' : ''}>● {pulse ? 'syncing' : 'live'}</em>
      </div>
      <div className="body">
        <div className="peers">
          <i>M</i><i>J</i><b>+ you</b>
        </div>
        <div className="canvas">
          <div className="frame">
            <span className="chrome" />
            <span className="hero" />
            <span className="cards" />
            {SCRIPT.filter((p) => shown.includes(p.id)).map((p) => (
              <div
                key={p.id}
                className={`pin ${resolved.includes(p.id) ? 'resolved' : ''}`}
                style={{ left: `${p.x}%`, top: `${p.y}%` }}
              >
                <b>{p.who === 'you' ? '·' : p.who}</b>
              </div>
            ))}
          </div>
        </div>
      </div>
    </Preview>
  );
}

/* ── FAQ row ───────────────────────────────────────────────────────────────── */
function Faq({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <FaqRow $open={open}>
      <button onClick={() => setOpen((o) => !o)}>
        <span>{q}</span>
        <i aria-hidden="true">{open ? '−' : '+'}</i>
      </button>
      <div className="ans"><p>{a}</p></div>
    </FaqRow>
  );
}

export default function LandingPage() {
  // Auth redirects (incl. desktop SSO skip) are handled by <RedirectIfAuthed>
  // in App.tsx, which waits for the async auth probe before navigating.

  // Real href keeps anchors keyboard-focusable; onClick upgrades to smooth scroll.
  const go = (id: string) => (e: React.MouseEvent) => {
    e.preventDefault();
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  return (
    <Root>
      {/* ── header ─────────────────────────────────────────────── */}
      <Header>
        <Brand>
          <span className="mark"><CalimeroLogo size={24} color={C.greenInk} /></span>
          <span className="wm">{APP_DISPLAY_NAME}</span>
        </Brand>
        <Nav>
          <a href="#how" onClick={go('how')}>How it works</a>
          <a href="#features" onClick={go('features')}>Features</a>
          <a href="#faq" onClick={go('faq')}>FAQ</a>
          <a href="https://docs.calimero.network" target="_blank" rel="noreferrer">Docs ↗</a>
          <a href="https://github.com/calimero-network" target="_blank" rel="noreferrer">GitHub ↗</a>
        </Nav>
        <div className="cta"><ConnectButton /></div>
      </Header>

      {/* ── hero ───────────────────────────────────────────────── */}
      <Hero>
        <Glow />
        <Grid />
        <HeroInner>
          <Eyebrow>
            <CalimeroLogo size={13} color={C.greenDeep} /> Powered by Calimero
          </Eyebrow>
          <H1>{APP_DISPLAY_NAME}</H1>
          <Lede>{APP_DESCRIPTION}</Lede>
          <Cta>
            <ConnectButton />
            <GhostBtn onClick={() => window.open('https://docs.calimero.network', '_blank', 'noopener,noreferrer')}>
              Learn more
            </GhostBtn>
          </Cta>
          <TrustRow>
            <span>Private by design</span><i />
            <span>Real-time sync</span><i />
            <span>Peer-to-peer</span>
          </TrustRow>
        </HeroInner>
        <PreviewWrap><LivePreview /></PreviewWrap>
      </Hero>

      {/* ── how it works ───────────────────────────────────────── */}
      <Section id="how" $alt>
        <Inner>
          <R v="up">
            <Kicker>How it works</Kicker>
            <H2>From your node to a shared app in four moves</H2>
            <Sub>No accounts, no servers, no setup friction. Connect a node and you’re collaborating.</Sub>
          </R>
          <Pipeline>
            <span className="track" />
            <span className="pulse" />
            {STEPS.map((s, i) => (
              <R v="drop" d={0.12 + i * 0.12} key={s.k}>
                <div className="stage">
                  <div className="dot"><b>{s.k}</b></div>
                  <h4>{s.t}</h4>
                  <p>{s.d}</p>
                </div>
              </R>
            ))}
          </Pipeline>
        </Inner>
      </Section>

      {/* ── features ───────────────────────────────────────────── */}
      <Section id="features">
        <Inner>
          <R v="up">
            <Kicker>Why it’s different</Kicker>
            <H2>Built on the Calimero network</H2>
          </R>
          <Cards>
            {FEATURES.map((f, i) => (
              <R v="drop" d={i * 0.12} key={f.title}>
                <FeatureCard>
                  <span className="ic">{f.icon}</span>
                  <h3>{f.title}</h3>
                  <p>{f.body}</p>
                </FeatureCard>
              </R>
            ))}
          </Cards>
        </Inner>
      </Section>

      {/* ── FAQ ────────────────────────────────────────────────── */}
      <Section id="faq" $alt>
        <Inner style={{ maxWidth: 760 }}>
          <R v="up">
            <Kicker>FAQ</Kicker>
            <H2>Nodes, contexts &amp; your data</H2>
          </R>
          <FaqList>
            {FAQS.map(([q, a], i) => (
              <R v="left" d={i * 0.06} key={q}><Faq q={q} a={a} /></R>
            ))}
          </FaqList>
        </Inner>
      </Section>

      {/* ── final CTA ──────────────────────────────────────────── */}
      <CtaBand>
        <R v="zoom">
          <h2>Connect your node to get started.</h2>
          <p>It takes seconds, and your data never leaves your control.</p>
          <div className="btn"><ConnectButton /></div>
        </R>
      </CtaBand>

      {/* ── footer ─────────────────────────────────────────────── */}
      <Footer>
        <div className="top">
          <div className="brand">
            <span className="wm"><span className="mk"><CalimeroLogo size={20} color={C.green} /></span> {APP_DISPLAY_NAME}</span>
            <p>Private. Real-time. Yours.</p>
          </div>
          <div className="cols">
            <div>
              <h5>App</h5>
              <a href="#how" onClick={go('how')}>How it works</a>
              <a href="#features" onClick={go('features')}>Features</a>
              <a href="#faq" onClick={go('faq')}>FAQ</a>
            </div>
            <div>
              <h5>Calimero</h5>
              <a href="https://calimero.network" target="_blank" rel="noreferrer">Website</a>
              <a href="https://docs.calimero.network" target="_blank" rel="noreferrer">Docs</a>
              <a href="https://github.com/calimero-network/core" target="_blank" rel="noreferrer">Core node</a>
            </div>
            <div>
              <h5>Community</h5>
              <a href="https://github.com/calimero-network" target="_blank" rel="noreferrer">GitHub</a>
              <a href="https://x.com/CalimeroNetwork" target="_blank" rel="noreferrer">X / Twitter</a>
              <a href="https://discord.gg/calimero" target="_blank" rel="noreferrer">Discord</a>
            </div>
          </div>
        </div>
        <div className="bottom">
          <span>Built on Calimero</span>
          <span>Self-sovereign by design</span>
        </div>
      </Footer>
    </Root>
  );
}

/* ════════════════════════ keyframes ════════════════════════ */
const float = keyframes`0%,100%{transform:translate(0,0) scale(1);}50%{transform:translate(14px,-18px) scale(1.05);}`;
const drift = keyframes`0%,100%{transform:translate(0,0) scale(1);}50%{transform:translate(-22px,14px) scale(1.07);}`;
const travel = keyframes`0%{left:0;opacity:0;}8%{opacity:1;}92%{opacity:1;}100%{left:100%;opacity:0;}`;
const rowIn = keyframes`from{opacity:0;transform:translateY(8px) scale(0.97);}to{opacity:1;transform:none;}`;

/* Page rhythm is fluid between two token steps rather than two raw px values,
   so a roomy preset breathes and a compact one tightens. */
const PAD_Y = 'clamp(var(--c-space-12), 8vw, calc(var(--c-space-16) * 1.6))';
const PAD_X = 'clamp(var(--c-space-5), 5vw, var(--c-space-16))';
const accentWash = (pct: number) => `color-mix(in srgb, var(--c-accent) ${pct}%, transparent)`;

/* ════════════════════════ layout ════════════════════════ */
const Root = styled.div`
  position: fixed;
  inset: 0;
  overflow-y: auto;
  overflow-x: hidden;
  background: ${C.paper};
  color: ${C.ink};
  font-family: var(--c-font-body);
  font-size: var(--c-text-base);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
`;

const Header = styled.header`
  position: sticky;
  top: 0;
  z-index: 50;
  display: flex;
  align-items: center;
  gap: var(--c-space-6);
  padding: var(--c-space-3) ${PAD_X};
  background: color-mix(in srgb, var(--c-paper) 82%, transparent);
  backdrop-filter: saturate(160%) blur(14px);
  border-bottom: 1px solid ${C.line};
  .cta { margin-left: auto; }
`;
const Brand = styled.div`
  display: flex;
  align-items: center;
  gap: var(--c-space-2);
  .mark { display: flex; }
  .wm {
    font-family: var(--c-font-display);
    letter-spacing: var(--c-display-tracking);
    font-size: var(--c-text-base);
    color: ${C.ink};
    font-weight: 700;
  }
`;
const Nav = styled.nav`
  display: flex;
  gap: var(--c-space-6);
  margin-left: auto;
  a {
    font-size: var(--c-text-base);
    font-weight: 500;
    color: ${C.muted};
    cursor: pointer;
    text-decoration: none;
    transition: color var(--c-duration-fast) var(--c-ease);
    &:hover { color: ${C.ink}; }
  }
  & + .cta { margin-left: 0; }
  @media ${WIDE} { display: none; }
`;

/* hero */
const Hero = styled.section`
  position: relative;
  overflow: hidden;
  display: grid;
  grid-template-columns: 1.05fr 0.95fr;
  gap: clamp(var(--c-space-6), 5vw, var(--c-space-16));
  align-items: center;
  padding: ${PAD_Y} ${PAD_X};
  background: radial-gradient(1200px 480px at 75% -10%, ${accentWash(18)} 0%, transparent 60%), ${C.paper};
  @media ${WIDE} { grid-template-columns: 1fr; }
  @media ${NARROW} { gap: var(--c-space-8); }
`;
const Glow = styled.div`
  position: absolute;
  width: 420px;
  height: 420px;
  border-radius: 50%;
  top: -140px;
  right: -80px;
  background: radial-gradient(circle, ${accentWash(50)}, transparent 68%);
  filter: blur(26px);
  animation: ${float} 11s ease-in-out infinite;
  pointer-events: none;
  @media (prefers-reduced-motion: reduce) { animation: none; }
`;
const Grid = styled.div`
  position: absolute;
  inset: 0;
  background-image: linear-gradient(${C.line} 1px, transparent 1px), linear-gradient(90deg, ${C.line} 1px, transparent 1px);
  background-size: 46px 46px;
  mask-image: radial-gradient(680px 380px at 30% 30%, black 0%, transparent 75%);
  opacity: 0.5;
  pointer-events: none;
`;
const HeroInner = styled.div`
  position: relative;
  z-index: 1;
  max-width: 580px;
`;
const Eyebrow = styled.div`
  display: inline-flex;
  align-items: center;
  gap: var(--c-space-2);
  font-size: var(--c-text-xs);
  font-weight: 600;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: ${C.accentText};
  background: ${accentWash(13)};
  border: 1px solid ${accentWash(40)};
  padding: var(--c-space-1) var(--c-space-3);
  border-radius: var(--c-radius-pill);
`;
const H1 = styled.h1`
  margin: var(--c-space-5) 0 var(--c-space-4);
  font-family: var(--c-font-display);
  font-size: clamp(calc(var(--c-text-2xl) * 1.2), 6vw, calc(var(--c-text-2xl) * 2));
  line-height: 1.03;
  letter-spacing: var(--c-display-tracking);
  font-weight: 800;
  color: ${C.ink};
`;
const Lede = styled.p`
  font-size: var(--c-text-lg);
  color: ${C.muted};
  max-width: 500px;
  margin-bottom: var(--c-space-6);
`;
const Cta = styled.div`
  display: flex;
  gap: var(--c-space-3);
  align-items: center;
  flex-wrap: wrap;
`;
const GhostBtn = styled(Secondary)`
  &:hover:not(:disabled) { transform: translateY(-1px); }
`;
const TrustRow = styled.div`
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--c-space-3);
  margin-top: var(--c-space-7);
  span { font-size: var(--c-text-sm); font-weight: 500; color: ${C.muted}; }
  i { width: 4px; height: 4px; border-radius: 50%; background: ${C.green}; }
`;

/* live preview: an app window, so it uses the same surfaces the app does */
const PreviewWrap = styled.div`
  position: relative;
  z-index: 1;
  animation: ${float} 9s ease-in-out infinite;
  @media ${WIDE} { animation: none; }
  @media (prefers-reduced-motion: reduce) { animation: none; }
`;
const Preview = styled.div`
  border: 1px solid ${C.line};
  border-radius: var(--c-radius-md);
  background: ${C.paper2};
  box-shadow: 0 30px 70px -30px ${C.shadow};
  overflow: hidden;
  .bar {
    display: flex;
    align-items: center;
    gap: var(--c-space-2);
    padding: var(--c-space-3) var(--c-space-3);
    border-bottom: 1px solid ${C.line};
    background: ${C.paper};
    s { width: 10px; height: 10px; border-radius: 50%; }
    span {
      margin-left: var(--c-space-2);
      display: inline-flex;
      align-items: center;
      gap: var(--c-space-2);
      font-size: var(--c-text-sm);
      color: ${C.mutedSoft};
      font-family: var(--c-font-mono);
    }
    em {
      margin-left: auto;
      font-style: normal;
      font-size: var(--c-text-xs);
      font-family: var(--c-font-mono);
      color: ${C.mutedSoft};
      transition: color var(--c-duration-base) var(--c-ease);
    }
    em.on { color: ${C.accentText}; }
  }
  .body { padding: var(--c-space-4); min-height: 230px; display: flex; flex-direction: column; gap: var(--c-space-3); }
  .peers { display: flex; align-items: center; gap: 0; }
  .peers i {
    width: 22px; height: 22px; border-radius: 50%;
    display: grid; place-items: center;
    font-size: var(--c-text-xs); font-weight: 700; color: ${C.accentInk};
    background: ${C.accent};
    border: 1.5px solid ${C.paper2};
    margin-left: -6px;
  }
  .peers i:first-child { margin-left: 0; }
  .peers b { margin-left: var(--c-space-2); font-size: var(--c-text-xs); font-weight: 600; color: ${C.mutedSoft}; }
  .canvas { position: relative; flex: 1; min-height: var(--c-space-16); }
  .frame {
    position: absolute; inset: 0;
    background: ${C.paper}; border: 1px solid ${C.line}; border-radius: var(--c-radius-sm);
    overflow: hidden;
  }
  .frame .chrome {
    position: absolute; top: 0; left: 0; right: 0; height: var(--c-space-5);
    background: ${C.paper2}; border-bottom: 1px solid ${C.line};
  }
  .frame .hero {
    position: absolute; top: var(--c-space-7); left: var(--c-space-3); right: var(--c-space-3);
    height: var(--c-space-8); background: ${C.paper2}; border-radius: var(--c-radius-sm);
  }
  .frame .cards {
    position: absolute; bottom: var(--c-space-3); left: var(--c-space-3); right: var(--c-space-3);
    height: var(--c-space-7); background: ${C.paper2}; border-radius: var(--c-radius-sm); opacity: 0.6;
  }
  .pin {
    position: absolute;
    width: var(--c-space-5); height: var(--c-space-5);
    transform: translate(-50%, -100%) rotate(45deg);
    border-radius: var(--c-radius-pill) var(--c-radius-pill) var(--c-radius-pill) 0;
    background: ${C.accent};
    border: 1.5px solid ${C.paper2};
    display: flex; align-items: center; justify-content: center;
    animation: ${rowIn} var(--c-duration-slow) var(--c-ease) both;
    transition: background var(--c-duration-base) var(--c-ease);
    b { transform: rotate(-45deg); font-size: var(--c-text-xs); font-weight: 700; color: ${C.accentInk}; }
  }
  .pin.resolved { background: ${C.green}; }
  .pin.resolved b { color: ${C.greenInk}; }
`;

/* sections */
const Section = styled.section<{ $alt?: boolean }>`
  padding: ${PAD_Y} ${PAD_X};
  background: ${(p) => (p.$alt ? C.paper2 : C.paper)};
  border-top: 1px solid ${C.line};
  scroll-margin-top: 76px;
`;
const Inner = styled.div`max-width: 1040px; margin: 0 auto;`;

const RBox = styled.div<{ $v: RVariant; $d: number }>`
  opacity: 0;
  will-change: opacity, transform;
  transform: ${(p) =>
    p.$v === 'zoom'
      ? 'scale(0.9)'
      : p.$v === 'drop'
        ? 'translateY(-46px)'
        : p.$v === 'left'
          ? 'translateX(-44px)'
          : 'translateY(30px)'};
  transition:
    opacity var(--c-duration-slow) ${(p) => p.$d}s var(--c-ease),
    transform var(--c-duration-slow) ${(p) => p.$d}s var(--c-ease);
  &.is-visible { opacity: 1; transform: none; }
  @media (prefers-reduced-motion: reduce) { opacity: 1; transform: none; transition: none; }
`;

const Kicker = styled.div`
  font-size: var(--c-text-xs);
  font-weight: 700;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: ${C.accentText};
  margin-bottom: var(--c-space-3);
`;
const H2 = styled.h2`
  font-family: var(--c-font-display);
  font-size: clamp(var(--c-text-xl), 3.4vw, calc(var(--c-text-2xl) * 1.15));
  line-height: 1.12;
  letter-spacing: var(--c-display-tracking);
  font-weight: 700;
  color: ${C.ink};
  max-width: 720px;
`;
const Sub = styled.p`margin-top: var(--c-space-3); font-size: var(--c-text-base); color: ${C.muted}; max-width: 600px;`;

/* pipeline */
const Pipeline = styled.div`
  position: relative;
  margin-top: var(--c-space-12);
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: var(--c-space-6);
  .track { position: absolute; top: 19px; left: 6%; right: 6%; height: 2px; background: linear-gradient(90deg, ${C.line}, ${accentWash(45)}, ${C.line}); }
  .pulse { position: absolute; top: 14px; width: 12px; height: 12px; border-radius: 50%; background: ${C.accent}; box-shadow: 0 0 0 5px ${accentWash(25)}; animation: ${travel} 4.2s ease-in-out infinite; }
  .stage { position: relative; text-align: left; }
  .dot {
    width: 40px; height: 40px; border-radius: var(--c-radius-md);
    display: grid; place-items: center;
    background: ${C.paper}; border: 1px solid ${C.line};
    box-shadow: 0 6px 16px -8px ${C.shadow};
    margin-bottom: var(--c-space-3);
  }
  .dot b { font-size: var(--c-text-base); font-weight: 700; color: ${C.accentText}; font-family: var(--c-font-mono); }
  .stage h4 {
    font-family: var(--c-font-display); letter-spacing: var(--c-display-tracking);
    font-size: var(--c-text-base); font-weight: 700; color: ${C.ink}; margin-bottom: var(--c-space-2);
  }
  .stage p { font-size: var(--c-text-base); color: ${C.muted}; }
  @media ${WIDE} {
    grid-template-columns: 1fr 1fr;
    .track, .pulse { display: none; }
  }
  @media (prefers-reduced-motion: reduce) { .pulse { animation: none; } }
`;

/* feature cards */
const Cards = styled.div`
  margin-top: var(--c-space-10);
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--c-space-4);
  @media ${WIDE} { grid-template-columns: 1fr; }
`;
const FeatureCard = styled.div`
  padding: var(--c-space-6) var(--c-space-6);
  border: 1px solid ${C.line};
  border-radius: var(--c-radius-md);
  background: ${C.paper};
  height: 100%;
  transition: transform var(--c-duration-base) var(--c-ease),
              box-shadow var(--c-duration-base) var(--c-ease),
              border-color var(--c-duration-base) var(--c-ease);
  .ic {
    display: grid; place-items: center; width: 42px; height: 42px;
    border-radius: var(--c-radius-md); background: ${accentWash(14)};
    color: ${C.accentText}; margin-bottom: var(--c-space-3);
  }
  .ic svg { width: 21px; height: 21px; }
  h3 {
    font-family: var(--c-font-display); letter-spacing: var(--c-display-tracking);
    font-size: var(--c-text-lg); font-weight: 700; color: ${C.ink}; margin-bottom: var(--c-space-2);
  }
  p { font-size: var(--c-text-base); color: ${C.muted}; }
  &:hover { transform: translateY(-3px); border-color: ${accentWash(60)}; box-shadow: 0 18px 40px -24px ${C.shadow}; }
`;

/* faq */
const FaqList = styled.div`margin-top: var(--c-space-8); border-top: 1px solid ${C.line};`;
const FaqRow = styled.div<{ $open: boolean }>`
  border-bottom: 1px solid ${C.line};
  button {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: var(--c-space-4);
    padding: var(--c-space-4) 0;
    background: none;
    border: none;
    cursor: pointer;
    text-align: left;
    font-family: inherit;
    font-size: var(--c-text-base);
    font-weight: 600;
    color: ${C.ink};
    i {
      font-style: normal; flex-shrink: 0; width: 24px; height: 24px;
      display: grid; place-items: center; border-radius: var(--c-radius-sm);
      font-size: var(--c-text-base); color: ${C.accentText}; background: ${accentWash(14)};
    }
  }
  .ans { overflow: hidden; max-height: ${(p) => (p.$open ? '240px' : '0')}; transition: max-height var(--c-duration-slow) var(--c-ease); }
  .ans p { padding: 0 0 var(--c-space-5); font-size: var(--c-text-base); color: ${C.muted}; max-width: 660px; }
`;

/* final CTA */
const CtaBand = styled.section`
  position: relative;
  overflow: hidden;
  text-align: center;
  padding: ${PAD_Y} var(--c-space-6);
  background: radial-gradient(700px 280px at 50% 120%, ${accentWash(22)}, transparent 70%), ${C.paper2};
  border-top: 1px solid ${C.line};
  h2 {
    font-family: var(--c-font-display); letter-spacing: var(--c-display-tracking);
    font-size: clamp(var(--c-text-xl), 3.6vw, calc(var(--c-text-2xl) * 1.2));
    font-weight: 700; color: ${C.ink};
  }
  p { margin: var(--c-space-3) 0 var(--c-space-6); font-size: var(--c-text-base); color: ${C.muted}; }
  .btn { display: inline-flex; }
  &::after {
    content: ''; position: absolute; width: 360px; height: 360px; border-radius: 50%;
    left: -120px; bottom: -180px;
    background: radial-gradient(circle, ${accentWash(30)}, transparent 68%);
    filter: blur(24px); animation: ${drift} 12s ease-in-out infinite;
  }
  @media (prefers-reduced-motion: reduce) { &::after { animation: none; } }
`;

/* footer */
const Footer = styled.footer`
  background: ${C.paper2};
  color: ${C.muted};
  border-top: 1px solid ${C.line};
  padding: var(--c-space-12) ${PAD_X} var(--c-space-7);
  .top { max-width: 1040px; margin: 0 auto; display: grid; grid-template-columns: 1.3fr 2fr; gap: var(--c-space-10); }
  @media ${WIDE} { .top { grid-template-columns: 1fr; gap: var(--c-space-7); } }
  .brand .wm {
    display: inline-flex; align-items: center; gap: var(--c-space-2);
    font-family: var(--c-font-display); letter-spacing: var(--c-display-tracking);
    font-size: var(--c-text-base); font-weight: 700; color: ${C.ink};
  }
  .brand .mk { display: flex; }
  .brand p { margin-top: var(--c-space-3); font-size: var(--c-text-base); max-width: 280px; }
  .cols { display: grid; grid-template-columns: repeat(3, 1fr); gap: var(--c-space-6); }
  @media ${NARROW} { .cols { grid-template-columns: 1fr 1fr; gap: var(--c-space-5) var(--c-space-6); } }
  .cols h5 { font-size: var(--c-text-xs); text-transform: uppercase; letter-spacing: 0.12em; color: ${C.ink}; margin-bottom: var(--c-space-3); }
  .cols a {
    display: block; font-size: var(--c-text-base); color: ${C.muted};
    text-decoration: none; margin-bottom: var(--c-space-2); cursor: pointer;
    transition: color var(--c-duration-fast) var(--c-ease);
    &:hover { color: ${C.accentText}; }
  }
  .bottom {
    max-width: 1040px; margin: var(--c-space-8) auto 0; padding-top: var(--c-space-5);
    border-top: 1px solid ${C.line}; display: flex; justify-content: space-between;
    gap: var(--c-space-3); font-size: var(--c-text-sm); flex-wrap: wrap;
  }
`;
