/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Event_EscrowDeposited {
  trade_id: string;
}

export interface Event_ListingCancelled {
  id: string;
}

export interface Event_ListingCreated {
  id: string;
}

export interface Event_OfferAccepted {
  offer_id: string;
  trade_id: string;
}

export interface Event_OfferMade {
  id: string;
  listing_id: string;
}

export interface Event_ProvenanceRecorded {
  item_id: string;
}

export interface Event_ReceiptConfirmed {
  trade_id: string;
}

export interface Listing {
  id: string;
  author: string;
  title: string;
  description: string;
  category: string;
  asking_price: number;
  condition: string;
  status: string;
  created_at: number;
}

export interface MarketplaceState {
  listings: Record<string, Listing>;
  offers: Record<string, Offer>;
  trades: Record<string, Trade>;
  provenance: Record<string, ProvenanceRecord>;
}

export interface Offer {
  id: string;
  author: string;
  listing_id: string;
  amount: number;
  status: string;
  created_at: number;
}

export interface ProvenanceRecord {
  item_id: string;
  prior_owner: string;
  price: number;
  sale_date: number;
  notes: string;
}

export interface Trade {
  id: string;
  listing_id: string;
  seller: string;
  buyer: string;
  amount: number;
  escrow_status: string;
  created_at: number;
}








export type AbiEvent =
  | { name: "ListingCreated"; payload: Event_ListingCreated }
  | { name: "ListingCancelled"; payload: Event_ListingCancelled }
  | { name: "OfferMade"; payload: Event_OfferMade }
  | { name: "OfferAccepted"; payload: Event_OfferAccepted }
  | { name: "EscrowDeposited"; payload: Event_EscrowDeposited }
  | { name: "ReceiptConfirmed"; payload: Event_ReceiptConfirmed }
  | { name: "ProvenanceRecorded"; payload: Event_ProvenanceRecorded }
;


export class MarketplaceClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * create_listing
   */
  public async createListing(params: { title: string; description: string; category: string; asking_price: number; condition: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_listing', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * list_active_listings
   */
  public async listActiveListings(): Promise<Listing[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_active_listings', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Listing[];
  }

  /**
   * get_listing
   */
  public async getListing(params: { id: string }): Promise<Listing> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_listing', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as Listing;
  }

  /**
   * cancel_listing
   */
  public async cancelListing(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'cancel_listing', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * make_offer
   */
  public async makeOffer(params: { listing_id: string; amount: number }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'make_offer', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * get_offers_for_listing
   */
  public async getOffersForListing(params: { listing_id: string }): Promise<Offer[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_offers_for_listing', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as Offer[];
  }

  /**
   * accept_offer
   */
  public async acceptOffer(params: { offer_id: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'accept_offer', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * deposit_to_escrow
   */
  public async depositToEscrow(params: { trade_id: string; amount: number }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'deposit_to_escrow', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * confirm_receipt
   */
  public async confirmReceipt(params: { trade_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'confirm_receipt', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_provenance
   */
  public async getProvenance(params: { item_id: string }): Promise<ProvenanceRecord[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_provenance', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as ProvenanceRecord[];
  }

  /**
   * record_provenance
   */
  public async recordProvenance(params: { item_id: string; prior_owner: string; price: number; sale_date: number; notes: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'record_provenance', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

}