/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface BalanceEntry {
  member: string;
  balance: number;
}

export interface Event_ExpenseAdded {
  id: string;
  paid_by: string;
  amount: number;
}

export interface Event_ExpenseDeleted {
  id: string;
}

export interface Event_ExpenseEdited {
  id: string;
}

export interface Event_GroupRenamed {
  name: string;
}

export interface Event_SettlementRecorded {
  id: string;
  from: string;
  to: string;
  amount: number;
}

export interface Expense {
  id: string;
  author: string;
  description: string;
  amount: number;
  paid_by: string;
  split_between: string[];
  created_at: number;
}

export interface ExpenseView {
  id: string;
  author: string;
  description: string;
  amount: number;
  paid_by: string;
  split_between: string[];
  created_at: number;
}

export interface GroupMetadata {
  id: string;
  name: string;
  created_at: number;
}

export interface GroupState {
  metadata: GroupMetadata;
  expenses: Record<string, Expense>;
  expense_authors: Record<string, number>;
  settlements: Record<string, Settlement>;
}

export interface Settlement {
  id: string;
  author: string;
  from: string;
  to: string;
  amount: number;
  created_at: number;
}

export interface SettlementView {
  id: string;
  author: string;
  from: string;
  to: string;
  amount: number;
  created_at: number;
}






export type AbiEvent =
  | { name: "ExpenseAdded"; payload: Event_ExpenseAdded }
  | { name: "ExpenseEdited"; payload: Event_ExpenseEdited }
  | { name: "ExpenseDeleted"; payload: Event_ExpenseDeleted }
  | { name: "SettlementRecorded"; payload: Event_SettlementRecorded }
  | { name: "GroupRenamed"; payload: Event_GroupRenamed }
;


export class GroupClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(params: { name: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * add_expense
   */
  public async addExpense(params: { description: string; amount: number; paid_by: string; split_between: string[] }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'add_expense', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * edit_expense
   */
  public async editExpense(params: { id: string; description: string; amount: number }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'edit_expense', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_expense
   */
  public async deleteExpense(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_expense', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_expenses
   */
  public async listExpenses(): Promise<ExpenseView[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_expenses', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as ExpenseView[];
  }

  /**
   * record_settlement
   */
  public async recordSettlement(params: { from: string; to: string; amount: number }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'record_settlement', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * list_settlements
   */
  public async listSettlements(): Promise<SettlementView[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_settlements', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as SettlementView[];
  }

  /**
   * get_balances
   */
  public async getBalances(): Promise<BalanceEntry[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_balances', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as BalanceEntry[];
  }

  /**
   * rename_group
   */
  public async renameGroup(params: { new_name: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'rename_group', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

}