/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface ChatState {
  messages: Record<string, Message>;
}

export interface Event_MessageDeleted {
  id: string;
}

export interface Event_MessageEdited {
  id: string;
}

export interface Event_MessageSent {
  id: string;
  author: string;
}

export interface Message {
  id: string;
  author: string;
  body: string;
  created_at: number;
  edited_at: number | null;
}




export type AbiEvent =
  | { name: "MessageSent"; payload: Event_MessageSent }
  | { name: "MessageEdited"; payload: Event_MessageEdited }
  | { name: "MessageDeleted"; payload: Event_MessageDeleted }
;


export class ChatClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * send_message
   */
  public async sendMessage(params: { body: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'send_message', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * edit_message
   */
  public async editMessage(params: { id: string; new_body: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'edit_message', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_message
   */
  public async deleteMessage(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_message', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_messages
   */
  public async listMessages(): Promise<Message[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_messages', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Message[];
  }

}