/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Counter {
  id: string;
  total: number;
  last_incremented_by: string;
  last_increment_at: number;
  creator: string;
}

export interface CounterState {
  counter: Record<string, {  }>;
}

export interface Event_CounterIncremented {
  by: string;
  total: number;
}

export interface Event_CounterReset {
  by: string;
}



export type AbiEvent =
  | { name: "CounterIncremented"; payload: Event_CounterIncremented }
  | { name: "CounterReset"; payload: Event_CounterReset }
;


export class CounterClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * increment
   */
  public async increment(): Promise<number> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'increment', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as number;
  }

  /**
   * reset
   */
  public async reset(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'reset', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_counter
   */
  public async getCounter(): Promise<Counter> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_counter', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as Counter;
  }

}