/** @generated by @calimero/abi-codegen — codegen fixes applied per BUILD AGENT rules. */

import { MeroJs } from '@calimero-network/mero-react';

// ── Generated types ──────────────────────────────────────────────────────────

export interface ClubSettings {
  id: string;
  name: string;
  weekly_goal: number;
  created_at: number;
}

export interface Workout {
  id: string;
  author: string;
  activity: string;
  duration_minutes: number;
  note: string;
  cheer_count: number;
  created_at: number;
}

export interface Cheer {
  id: string;
  author: string;
  workout_id: string;
  created_at: number;
}

// ── Event payloads ───────────────────────────────────────────────────────────

export interface Event_ClubInitialized { id: string; }
export interface Event_WeeklyGoalUpdated { goal: number; }
export interface Event_WorkoutLogged { id: string; author: string; }
export interface Event_WorkoutEdited { id: string; }
export interface Event_WorkoutDeleted { id: string; }
export interface Event_CheerAdded { id: string; workout_id: string; }

export type AbiEvent =
  | { name: 'ClubInitialized'; payload: Event_ClubInitialized }
  | { name: 'WeeklyGoalUpdated'; payload: Event_WeeklyGoalUpdated }
  | { name: 'WorkoutLogged'; payload: Event_WorkoutLogged }
  | { name: 'WorkoutEdited'; payload: Event_WorkoutEdited }
  | { name: 'WorkoutDeleted'; payload: Event_WorkoutDeleted }
  | { name: 'CheerAdded'; payload: Event_CheerAdded };

// ── Client ───────────────────────────────────────────────────────────────────

export class ClubClient {
  private _mero: MeroJs;
  // Fix: private field renamed _contextId to avoid collision with any
  // future context_id() method (codegen fix #3).
  private _contextId: string;
  // Fix: private field renamed _executorPublicKey to avoid collision with
  // any future executor_public_key() method (codegen fix #4).
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /** Standard WASM initializer — called automatically by createContext. */
  public async init(): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'init',
      argsJson: {},
      executorPublicKey: this._executorPublicKey,
    });
  }

  /** Initialize club with a name and weekly workout goal. Call once after createContext. */
  public async initClub(params: { name: string; weekly_goal: number }): Promise<string> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'init_club',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
    return response as string;
  }

  /** Update the weekly workout goal (creator only). */
  public async setWeeklyGoal(params: { goal: number }): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'set_weekly_goal',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
  }

  /** Read current club settings (name, weekly_goal, created_at). */
  public async getClubSettings(): Promise<ClubSettings> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'get_club_settings',
      argsJson: {},
      executorPublicKey: this._executorPublicKey,
    });
    return response as ClubSettings;
  }

  /** Log a new workout entry. Returns the new workout id. */
  public async logWorkout(params: {
    activity: string;
    duration_minutes: number;
    note: string;
  }): Promise<string> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'log_workout',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
    return response as string;
  }

  /** Edit an existing workout (author-only). */
  public async editWorkout(params: {
    id: string;
    activity: string;
    duration_minutes: number;
    note: string;
  }): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'edit_workout',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
  }

  /** Delete a workout (author-only). */
  public async deleteWorkout(params: { id: string }): Promise<void> {
    await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'delete_workout',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
  }

  /** Fetch all workouts for this club. */
  public async getWorkouts(): Promise<Workout[]> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'get_workouts',
      argsJson: {},
      executorPublicKey: this._executorPublicKey,
    });
    return response as Workout[];
  }

  /** Add a cheer to a workout. Returns the new cheer id. */
  public async addCheer(params: { workout_id: string }): Promise<string> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'add_cheer',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
    return response as string;
  }

  /** Get all cheers for a specific workout. */
  public async getCheers(params: { workout_id: string }): Promise<Cheer[]> {
    const response = await this._mero.rpc.execute({
      contextId: this._contextId,
      method: 'get_cheers',
      argsJson: params,
      executorPublicKey: this._executorPublicKey,
    });
    return response as Cheer[];
  }
}
